#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

NUM_ROBOTS="${NUM_ROBOTS:-5}"
MAX_UPDATES="${MAX_UPDATES:-4}"
DATASET_FILTER="${DATASETS:-sphere,torus}"
MANUAL_SCHEME="${MANUAL_SCHEME:-${SCHEME:-mm}}"
MANUAL_ACCELERATED="${MANUAL_ACCELERATED:-${ACCELERATED:-false}}"
LOCAL_SOLVER="${LOCAL_SOLVER:-reduced_rotation}"
REDUCED_ROTATION_PRECONDITIONER="${REDUCED_ROTATION_PRECONDITIONER:-none}"
LOCAL_MAX_ITERATIONS="${LOCAL_MAX_ITERATIONS:-1}"
LOCAL_MAX_ITERATIONS_ACCEPTED="${LOCAL_MAX_ITERATIONS_ACCEPTED:-1}"
LOCAL_MAX_TCG_ITERATIONS="${LOCAL_MAX_TCG_ITERATIONS:-10}"
ADAPTIVE_REDUCED_TCG="${ADAPTIVE_REDUCED_TCG:-false}"
ADAPTIVE_REDUCED_TCG_MAX_ITERATIONS="${ADAPTIVE_REDUCED_TCG_MAX_ITERATIONS:-50}"
ADAPTIVE_REDUCED_TCG_GRADIENT_RATIO="${ADAPTIVE_REDUCED_TCG_GRADIENT_RATIO:-0.15}"
REDUCED_ROTATION_TCG_RELATIVE_TOLERANCE="${REDUCED_ROTATION_TCG_RELATIVE_TOLERANCE:-0.1}"
LOCAL_STATE_EXTRAPOLATION="${LOCAL_STATE_EXTRAPOLATION:-false}"
LOCAL_STATE_EXTRAPOLATION_GAMMA="${LOCAL_STATE_EXTRAPOLATION_GAMMA:-0.5}"
LOCAL_STATE_EXTRAPOLATION_GAMMAS="${LOCAL_STATE_EXTRAPOLATION_GAMMAS:-}"
LOCAL_MODEL_G_EXTRAPOLATION="${LOCAL_MODEL_G_EXTRAPOLATION:-false}"
LOCAL_MODEL_G_EXTRAPOLATION_GAMMA="${LOCAL_MODEL_G_EXTRAPOLATION_GAMMA:-0.5}"
LOCAL_MODEL_G_EXTRAPOLATION_GAMMAS="${LOCAL_MODEL_G_EXTRAPOLATION_GAMMAS:-}"
COUPLED_STATE_G_EXTRAPOLATION="${COUPLED_STATE_G_EXTRAPOLATION:-false}"
COUPLED_STATE_G_EXTRAPOLATION_GAMMA="${COUPLED_STATE_G_EXTRAPOLATION_GAMMA:-0.5}"
COUPLED_STATE_G_EXTRAPOLATION_GAMMAS="${COUPLED_STATE_G_EXTRAPOLATION_GAMMAS:-}"
LOCAL_ANDERSON_ACCELERATION="${LOCAL_ANDERSON_ACCELERATION:-false}"
LOCAL_ANDERSON_MAX_ALPHA="${LOCAL_ANDERSON_MAX_ALPHA:-1}"
LOCAL_CANDIDATE_COST_TIE_TOLERANCE="${LOCAL_CANDIDATE_COST_TIE_TOLERANCE:-0}"
GLOBAL_STATE_EXTRAPOLATION="${GLOBAL_STATE_EXTRAPOLATION:-false}"
GLOBAL_STATE_EXTRAPOLATION_GAMMA="${GLOBAL_STATE_EXTRAPOLATION_GAMMA:-0.5}"
GLOBAL_STATE_EXTRAPOLATION_GAMMAS="${GLOBAL_STATE_EXTRAPOLATION_GAMMAS:-}"
GLOBAL_ANDERSON_ACCELERATION="${GLOBAL_ANDERSON_ACCELERATION:-false}"
GLOBAL_ANDERSON_MAX_ALPHA="${GLOBAL_ANDERSON_MAX_ALPHA:-1}"
LOCAL_GRADIENT_CORRECTION="${LOCAL_GRADIENT_CORRECTION:-false}"
LOCAL_GRADIENT_CORRECTION_STEP="${LOCAL_GRADIENT_CORRECTION_STEP:-1e-3}"
LOCAL_GRADIENT_CORRECTION_STEPS="${LOCAL_GRADIENT_CORRECTION_STEPS:-}"
LOCAL_GRADIENT_CORRECTION_SHARED_STEP="${LOCAL_GRADIENT_CORRECTION_SHARED_STEP:-false}"
LOCAL_GRADIENT_CORRECTION_NEIGHBORHOOD_STEP="${LOCAL_GRADIENT_CORRECTION_NEIGHBORHOOD_STEP:-false}"
LOCAL_GRADIENT_CORRECTION_CURVATURE_STEP="${LOCAL_GRADIENT_CORRECTION_CURVATURE_STEP:-false}"
LOCAL_GRADIENT_CORRECTION_COUPLED_DIRECTION="${LOCAL_GRADIENT_CORRECTION_COUPLED_DIRECTION:-false}"
LOCAL_GRADIENT_CORRECTION_COUPLED_DIRECTION_BUDGET_FRACTION="${LOCAL_GRADIENT_CORRECTION_COUPLED_DIRECTION_BUDGET_FRACTION:-1}"
LOCAL_GRADIENT_CORRECTION_COUPLED_DIRECTION_MAX_PACKETS_PER_RECEIVER="${LOCAL_GRADIENT_CORRECTION_COUPLED_DIRECTION_MAX_PACKETS_PER_RECEIVER:-0}"
LOCAL_GRADIENT_CORRECTION_COUPLED_DIRECTION_TOPK_ENTRIES="${LOCAL_GRADIENT_CORRECTION_COUPLED_DIRECTION_TOPK_ENTRIES:-0}"
LOCAL_GRADIENT_CORRECTION_COUPLED_DIRECTION_MIN_SCORE="${LOCAL_GRADIENT_CORRECTION_COUPLED_DIRECTION_MIN_SCORE:-0}"
LOCAL_GRADIENT_CORRECTION_COUPLED_DIRECTION_MIN_SCORE_RATIO="${LOCAL_GRADIENT_CORRECTION_COUPLED_DIRECTION_MIN_SCORE_RATIO:-0}"
LOCAL_GRADIENT_CORRECTION_COUPLED_DIRECTION_BYTE_BUDGET_MB="${LOCAL_GRADIENT_CORRECTION_COUPLED_DIRECTION_BYTE_BUDGET_MB:-0}"
LOCAL_GRADIENT_CORRECTION_BOUNDARY_ONLY="${LOCAL_GRADIENT_CORRECTION_BOUNDARY_ONLY:-false}"
LOCAL_GRADIENT_CORRECTION_BLOCK_JACOBI="${LOCAL_GRADIENT_CORRECTION_BLOCK_JACOBI:-false}"
LOCAL_GRADIENT_CORRECTION_COMPACT_SCHUR="${LOCAL_GRADIENT_CORRECTION_COMPACT_SCHUR:-false}"
LOCAL_GRADIENT_CORRECTION_COMPACT_SCHUR_MAX_BOUNDARY_POSES="${LOCAL_GRADIENT_CORRECTION_COMPACT_SCHUR_MAX_BOUNDARY_POSES:-32}"
LOCAL_GRADIENT_CORRECTION_COMPACT_SCHUR_MAX_PRIVATE_COLS="${LOCAL_GRADIENT_CORRECTION_COMPACT_SCHUR_MAX_PRIVATE_COLS:-64}"
LOCAL_GRADIENT_CORRECTION_COMPACT_SCHUR_DAMPING="${LOCAL_GRADIENT_CORRECTION_COMPACT_SCHUR_DAMPING:-1e-6}"
LOCAL_GRADIENT_CORRECTION_COMPACT_SCHUR_GRADIENT_GUARD="${LOCAL_GRADIENT_CORRECTION_COMPACT_SCHUR_GRADIENT_GUARD:-false}"
LOCAL_GRADIENT_CORRECTION_COMPACT_SCHUR_MAX_GRADIENT_INCREASE_RATIO="${LOCAL_GRADIENT_CORRECTION_COMPACT_SCHUR_MAX_GRADIENT_INCREASE_RATIO:-0}"
LOCAL_GRADIENT_CORRECTION_FRESH_NEIGHBOR_EXCHANGE="${LOCAL_GRADIENT_CORRECTION_FRESH_NEIGHBOR_EXCHANGE:-false}"
LOCAL_GRADIENT_CORRECTION_FRESH_MIN_POSE_DELTA="${LOCAL_GRADIENT_CORRECTION_FRESH_MIN_POSE_DELTA:-0}"
LOCAL_GRADIENT_CORRECTION_FRESH_DELTA_MODE="${LOCAL_GRADIENT_CORRECTION_FRESH_DELTA_MODE:-absolute}"
LOCAL_GRADIENT_CORRECTION_FRESH_BUDGET_FRACTION="${LOCAL_GRADIENT_CORRECTION_FRESH_BUDGET_FRACTION:-1}"
LOCAL_GRADIENT_CORRECTION_FRESH_MAX_POSES_PER_RECEIVER="${LOCAL_GRADIENT_CORRECTION_FRESH_MAX_POSES_PER_RECEIVER:-0}"
LOCAL_GRADIENT_CORRECTION_INNER_ROUNDS="${LOCAL_GRADIENT_CORRECTION_INNER_ROUNDS:-1}"
LOCAL_GRADIENT_CORRECTION_MAX_ROUNDS="${LOCAL_GRADIENT_CORRECTION_MAX_ROUNDS:-0}"
POST_EXCHANGE_PERIOD="${POST_EXCHANGE_PERIOD:-1}"
POST_EXCHANGE_MIN_POSE_DELTA="${POST_EXCHANGE_MIN_POSE_DELTA:-0}"
POST_EXCHANGE_DELTA_MODE="${POST_EXCHANGE_DELTA_MODE:-absolute}"
POST_EXCHANGE_BUDGET_FRACTION="${POST_EXCHANGE_BUDGET_FRACTION:-1}"
POST_EXCHANGE_MAX_POSES_PER_RECEIVER="${POST_EXCHANGE_MAX_POSES_PER_RECEIVER:-0}"
SYNC_AMM_REFERENCE_AFTER_LOCAL_GRADIENT_CORRECTION="${SYNC_AMM_REFERENCE_AFTER_LOCAL_GRADIENT_CORRECTION:-true}"
GLOBAL_GRADIENT_CORRECTION="${GLOBAL_GRADIENT_CORRECTION:-false}"
GLOBAL_GRADIENT_CORRECTION_STEP="${GLOBAL_GRADIENT_CORRECTION_STEP:-1e-3}"
GLOBAL_GRADIENT_CORRECTION_STEPS="${GLOBAL_GRADIENT_CORRECTION_STEPS:-}"
RESET_LOCAL_HISTORY_AFTER_GLOBAL_CORRECTION="${RESET_LOCAL_HISTORY_AFTER_GLOBAL_CORRECTION:-false}"
SYNC_AMM_REFERENCE_AFTER_GLOBAL_CORRECTION="${SYNC_AMM_REFERENCE_AFTER_GLOBAL_CORRECTION:-false}"
AMM_DPGO_SURROGATE_PARITY="${AMM_DPGO_SURROGATE_PARITY:-false}"
AMM_DPGO_RECURSIVE_SIMPLE_STATE="${AMM_DPGO_RECURSIVE_SIMPLE_STATE:-false}"
AMM_RECURSIVE_SIMPLE_REANCHOR_PERIOD="${AMM_RECURSIVE_SIMPLE_REANCHOR_PERIOD:-0}"
AMM_DPGO_STRICT_REFINED_GATE="${AMM_DPGO_STRICT_REFINED_GATE:-false}"
AMM_DPGO_RECOVER_TRANSLATIONS_AFTER_PROXIMAL="${AMM_DPGO_RECOVER_TRANSLATIONS_AFTER_PROXIMAL:-false}"
AMM_DPGO_REFINED_STARTS_AT_RECOVERED_PROXIMAL="${AMM_DPGO_REFINED_STARTS_AT_RECOVERED_PROXIMAL:-false}"
AMM_DPGO_MIXED_SURROGATE_PORTFOLIO="${AMM_DPGO_MIXED_SURROGATE_PORTFOLIO:-false}"
AMM_MIXED_SURROGATE_SKIP_SIMPLE_AFTER_TRUE_LOCAL_STREAK="${AMM_MIXED_SURROGATE_SKIP_SIMPLE_AFTER_TRUE_LOCAL_STREAK:-0}"
AMM_MIXED_SURROGATE_FORCE_SIMPLE_EVERY_SKIPPED_ROUNDS="${AMM_MIXED_SURROGATE_FORCE_SIMPLE_EVERY_SKIPPED_ROUNDS:-0}"
DPGO_MM_LOCAL_MAX_TCG_ITERATIONS="${DPGO_MM_LOCAL_MAX_TCG_ITERATIONS:-10000}"
DPGO_MM_AMM_TRACE="${DPGO_MM_AMM_TRACE:-${AMM_TRACE:-false}}"
TRACE_AMM="${TRACE_AMM:-false}"
MANUAL_BIN="${MANUAL_BIN:-${BIN:-}}"
DPGO_MM_BIN="${DPGO_MM_BIN:-}"
DIST_INIT="${DIST_INIT:-false}"
DRY_RUN="${DRY_RUN:-false}"
PAIRWISE_ONLY="${PAIRWISE_ONLY:-false}"
OUT_ROOT="${OUT_ROOT:-${ROOT_DIR}/results/manual_dpgo_mm_replay_compare_$(date +%Y%m%d_%H%M%S)}"

if [[ "${OUT_ROOT}" != /* ]]; then
  OUT_ROOT="${ROOT_DIR}/${OUT_ROOT}"
fi

COMPARISON_CSV="${OUT_ROOT}/comparison.csv"
PAIRWISE_CSV="${OUT_ROOT}/pairwise_cost_delta.csv"

sanitize() {
  local value="$1"
  printf '%s' "${value}" | tr '[:upper:]' '[:lower:]'
}

csv_value() {
  local file="$1"
  local column="$2"
  awk -F, -v column="${column}" '
    NR == 1 {
      for (i = 1; i <= NF; ++i) {
        if ($i == column) {
          idx = i
        }
      }
    }
    NR == 2 && idx > 0 {
      print $idx
    }
  ' "${file}"
}

print_dry_run() {
  local variant="$1"
  local dataset="$2"
  shift 2
  printf '%s,%s,updates=%s ' "${variant}" "${dataset}" "${MAX_UPDATES}"
  printf '%q ' "$@"
  printf '\n'
}

append_summary_row() {
  local dataset="$1"
  local updates="$2"
  local variant="$3"
  local run_root="$4"
  local summary="${run_root}/summary.csv"

  local status="missing_summary"
  local cost=""
  local gradient=""
  local comm_mb=""
  local wall_time=""
  local solver_time=""
  if [[ -f "${summary}" ]]; then
    status="$(csv_value "${summary}" "status")"
    cost="$(csv_value "${summary}" "global_cost")"
    gradient="$(csv_value "${summary}" "gradient")"
    comm_mb="$(csv_value "${summary}" "total_comm_mb")"
    wall_time="$(csv_value "${summary}" "wall_time_sec")"
    solver_time="$(csv_value "${summary}" "solver_time_per_node_sec")"
  fi

  printf '%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s\n' \
    "${dataset}" "${updates}" "${variant}" "${status}" "${cost}" \
    "${gradient}" "${comm_mb}" "${wall_time}" "${solver_time}" \
    "${run_root}" "${summary}" >> "${COMPARISON_CSV}"
}

write_pairwise_table() {
  {
    printf '%s\n' "dataset,updates,baseline,manual_cost,baseline_cost,manual_minus_baseline,manual_better"
    awk -F, '
    NR == 1 { next }
    {
      key = $1 "," $2
      cost[key "," $3] = $5
      status[key "," $3] = $4
    }
    END {
      for (key_variant in cost) {
        split(key_variant, parts, ",")
        dataset = parts[1]
        updates = parts[2]
        variant = parts[3]
        if (variant != "manual_reduced") {
          continue
        }
        key = dataset "," updates
        manual = cost[key ",manual_reduced"]
        for (baseline_idx = 1; baseline_idx <= 2; ++baseline_idx) {
          baseline = baseline_idx == 1 ? "dpgo_mm_mm" : "dpgo_mm_amm"
          base = cost[key "," baseline]
          if (manual == "" || base == "") {
            delta = ""
            better = "unknown"
          } else {
            delta = manual - base
            better = delta < 0 ? "true" : "false"
          }
          print dataset "," updates "," baseline "," manual "," base "," delta "," better
        }
      }
    }
    ' "${COMPARISON_CSV}" | sort
  } > "${PAIRWISE_CSV}"
}

IFS=',' read -r -a DATASET_ORDER <<< "${DATASET_FILTER}"

manual_bin_env=()
if [[ -n "${MANUAL_BIN}" ]]; then
  manual_bin_env=(BIN="${MANUAL_BIN}")
fi
dpgo_mm_bin_env=()
if [[ -n "${DPGO_MM_BIN}" ]]; then
  dpgo_mm_bin_env=(BIN="${DPGO_MM_BIN}")
fi

if [[ "$(sanitize "${PAIRWISE_ONLY}")" == "true" || "${PAIRWISE_ONLY}" == "1" ]]; then
  if [[ ! -f "${COMPARISON_CSV}" ]]; then
    echo "Missing comparison CSV for PAIRWISE_ONLY: ${COMPARISON_CSV}" >&2
    exit 1
  fi
  write_pairwise_table
  echo "Saved pairwise deltas: ${PAIRWISE_CSV}"
  exit 0
fi

if [[ "$(sanitize "${DRY_RUN}")" == "true" || "${DRY_RUN}" == "1" ]]; then
  for dataset in "${DATASET_ORDER[@]}"; do
    print_dry_run "dpgo_mm_mm" "${dataset}" env -u BIN \
      "${dpgo_mm_bin_env[@]}" \
      DATASETS="${dataset}" NUM_ROBOTS="${NUM_ROBOTS}" \
      MAX_ITERS="$((MAX_UPDATES + 1))" SCHEME=mm ACCELERATED=false \
      DIST_INIT="${DIST_INIT}" LOCAL_MAX_ITERATIONS="${LOCAL_MAX_ITERATIONS}" \
      LOCAL_MAX_ITERATIONS_ACCEPTED="${LOCAL_MAX_ITERATIONS_ACCEPTED}" \
      LOCAL_MAX_TCG_ITERATIONS="${DPGO_MM_LOCAL_MAX_TCG_ITERATIONS}" \
      AMM_TRACE="${DPGO_MM_AMM_TRACE}" \
      OUT_ROOT="${OUT_ROOT}/dpgo_mm_mm/${dataset}" \
      ./scripts/run_dpgo_mm_six.sh
    print_dry_run "dpgo_mm_amm" "${dataset}" env -u BIN \
      "${dpgo_mm_bin_env[@]}" \
      DATASETS="${dataset}" NUM_ROBOTS="${NUM_ROBOTS}" \
      MAX_ITERS="$((MAX_UPDATES + 1))" SCHEME=amm ACCELERATED=true \
      DIST_INIT="${DIST_INIT}" LOCAL_MAX_ITERATIONS="${LOCAL_MAX_ITERATIONS}" \
      LOCAL_MAX_ITERATIONS_ACCEPTED="${LOCAL_MAX_ITERATIONS_ACCEPTED}" \
      LOCAL_MAX_TCG_ITERATIONS="${DPGO_MM_LOCAL_MAX_TCG_ITERATIONS}" \
      AMM_TRACE="${DPGO_MM_AMM_TRACE}" \
      OUT_ROOT="${OUT_ROOT}/dpgo_mm_amm/${dataset}" \
      ./scripts/run_dpgo_mm_six.sh
    print_dry_run "manual_reduced" "${dataset}" env \
      "${manual_bin_env[@]}" \
      DATASETS="${dataset}" NUM_ROBOTS="${NUM_ROBOTS}" \
      MAX_ITERS="${MAX_UPDATES}" SCHEME="${MANUAL_SCHEME}" \
      ACCELERATED="${MANUAL_ACCELERATED}" LOCAL_SOLVER="${LOCAL_SOLVER}" \
      REDUCED_ROTATION_PRECONDITIONER="${REDUCED_ROTATION_PRECONDITIONER}" \
      LOCAL_MAX_ITERATIONS="${LOCAL_MAX_ITERATIONS}" \
      LOCAL_MAX_ITERATIONS_ACCEPTED="${LOCAL_MAX_ITERATIONS_ACCEPTED}" \
      LOCAL_MAX_TCG_ITERATIONS="${LOCAL_MAX_TCG_ITERATIONS}" \
      ADAPTIVE_REDUCED_TCG="${ADAPTIVE_REDUCED_TCG}" \
      ADAPTIVE_REDUCED_TCG_MAX_ITERATIONS="${ADAPTIVE_REDUCED_TCG_MAX_ITERATIONS}" \
      ADAPTIVE_REDUCED_TCG_GRADIENT_RATIO="${ADAPTIVE_REDUCED_TCG_GRADIENT_RATIO}" \
      REDUCED_ROTATION_TCG_RELATIVE_TOLERANCE="${REDUCED_ROTATION_TCG_RELATIVE_TOLERANCE}" \
      LOCAL_STATE_EXTRAPOLATION="${LOCAL_STATE_EXTRAPOLATION}" \
      LOCAL_STATE_EXTRAPOLATION_GAMMA="${LOCAL_STATE_EXTRAPOLATION_GAMMA}" \
      LOCAL_STATE_EXTRAPOLATION_GAMMAS="${LOCAL_STATE_EXTRAPOLATION_GAMMAS}" \
      LOCAL_MODEL_G_EXTRAPOLATION="${LOCAL_MODEL_G_EXTRAPOLATION}" \
      LOCAL_MODEL_G_EXTRAPOLATION_GAMMA="${LOCAL_MODEL_G_EXTRAPOLATION_GAMMA}" \
      LOCAL_MODEL_G_EXTRAPOLATION_GAMMAS="${LOCAL_MODEL_G_EXTRAPOLATION_GAMMAS}" \
      COUPLED_STATE_G_EXTRAPOLATION="${COUPLED_STATE_G_EXTRAPOLATION}" \
      COUPLED_STATE_G_EXTRAPOLATION_GAMMA="${COUPLED_STATE_G_EXTRAPOLATION_GAMMA}" \
      COUPLED_STATE_G_EXTRAPOLATION_GAMMAS="${COUPLED_STATE_G_EXTRAPOLATION_GAMMAS}" \
      LOCAL_ANDERSON_ACCELERATION="${LOCAL_ANDERSON_ACCELERATION}" \
      LOCAL_ANDERSON_MAX_ALPHA="${LOCAL_ANDERSON_MAX_ALPHA}" \
      LOCAL_CANDIDATE_COST_TIE_TOLERANCE="${LOCAL_CANDIDATE_COST_TIE_TOLERANCE}" \
      GLOBAL_STATE_EXTRAPOLATION="${GLOBAL_STATE_EXTRAPOLATION}" \
      GLOBAL_STATE_EXTRAPOLATION_GAMMA="${GLOBAL_STATE_EXTRAPOLATION_GAMMA}" \
      GLOBAL_STATE_EXTRAPOLATION_GAMMAS="${GLOBAL_STATE_EXTRAPOLATION_GAMMAS}" \
      GLOBAL_ANDERSON_ACCELERATION="${GLOBAL_ANDERSON_ACCELERATION}" \
      GLOBAL_ANDERSON_MAX_ALPHA="${GLOBAL_ANDERSON_MAX_ALPHA}" \
      LOCAL_GRADIENT_CORRECTION="${LOCAL_GRADIENT_CORRECTION}" \
      LOCAL_GRADIENT_CORRECTION_STEP="${LOCAL_GRADIENT_CORRECTION_STEP}" \
      LOCAL_GRADIENT_CORRECTION_STEPS="${LOCAL_GRADIENT_CORRECTION_STEPS}" \
      LOCAL_GRADIENT_CORRECTION_SHARED_STEP="${LOCAL_GRADIENT_CORRECTION_SHARED_STEP}" \
      LOCAL_GRADIENT_CORRECTION_NEIGHBORHOOD_STEP="${LOCAL_GRADIENT_CORRECTION_NEIGHBORHOOD_STEP}" \
      LOCAL_GRADIENT_CORRECTION_CURVATURE_STEP="${LOCAL_GRADIENT_CORRECTION_CURVATURE_STEP}" \
      LOCAL_GRADIENT_CORRECTION_COUPLED_DIRECTION="${LOCAL_GRADIENT_CORRECTION_COUPLED_DIRECTION}" \
      LOCAL_GRADIENT_CORRECTION_COUPLED_DIRECTION_BUDGET_FRACTION="${LOCAL_GRADIENT_CORRECTION_COUPLED_DIRECTION_BUDGET_FRACTION}" \
      LOCAL_GRADIENT_CORRECTION_COUPLED_DIRECTION_MAX_PACKETS_PER_RECEIVER="${LOCAL_GRADIENT_CORRECTION_COUPLED_DIRECTION_MAX_PACKETS_PER_RECEIVER}" \
      LOCAL_GRADIENT_CORRECTION_COUPLED_DIRECTION_TOPK_ENTRIES="${LOCAL_GRADIENT_CORRECTION_COUPLED_DIRECTION_TOPK_ENTRIES}" \
      LOCAL_GRADIENT_CORRECTION_COUPLED_DIRECTION_MIN_SCORE="${LOCAL_GRADIENT_CORRECTION_COUPLED_DIRECTION_MIN_SCORE}" \
      LOCAL_GRADIENT_CORRECTION_COUPLED_DIRECTION_MIN_SCORE_RATIO="${LOCAL_GRADIENT_CORRECTION_COUPLED_DIRECTION_MIN_SCORE_RATIO}" \
      LOCAL_GRADIENT_CORRECTION_COUPLED_DIRECTION_BYTE_BUDGET_MB="${LOCAL_GRADIENT_CORRECTION_COUPLED_DIRECTION_BYTE_BUDGET_MB}" \
      LOCAL_GRADIENT_CORRECTION_BOUNDARY_ONLY="${LOCAL_GRADIENT_CORRECTION_BOUNDARY_ONLY}" \
      LOCAL_GRADIENT_CORRECTION_BLOCK_JACOBI="${LOCAL_GRADIENT_CORRECTION_BLOCK_JACOBI}" \
      LOCAL_GRADIENT_CORRECTION_COMPACT_SCHUR="${LOCAL_GRADIENT_CORRECTION_COMPACT_SCHUR}" \
      LOCAL_GRADIENT_CORRECTION_COMPACT_SCHUR_MAX_BOUNDARY_POSES="${LOCAL_GRADIENT_CORRECTION_COMPACT_SCHUR_MAX_BOUNDARY_POSES}" \
      LOCAL_GRADIENT_CORRECTION_COMPACT_SCHUR_MAX_PRIVATE_COLS="${LOCAL_GRADIENT_CORRECTION_COMPACT_SCHUR_MAX_PRIVATE_COLS}" \
      LOCAL_GRADIENT_CORRECTION_COMPACT_SCHUR_DAMPING="${LOCAL_GRADIENT_CORRECTION_COMPACT_SCHUR_DAMPING}" \
      LOCAL_GRADIENT_CORRECTION_COMPACT_SCHUR_GRADIENT_GUARD="${LOCAL_GRADIENT_CORRECTION_COMPACT_SCHUR_GRADIENT_GUARD}" \
      LOCAL_GRADIENT_CORRECTION_COMPACT_SCHUR_MAX_GRADIENT_INCREASE_RATIO="${LOCAL_GRADIENT_CORRECTION_COMPACT_SCHUR_MAX_GRADIENT_INCREASE_RATIO}" \
      LOCAL_GRADIENT_CORRECTION_FRESH_NEIGHBOR_EXCHANGE="${LOCAL_GRADIENT_CORRECTION_FRESH_NEIGHBOR_EXCHANGE}" \
      LOCAL_GRADIENT_CORRECTION_FRESH_MIN_POSE_DELTA="${LOCAL_GRADIENT_CORRECTION_FRESH_MIN_POSE_DELTA}" \
      LOCAL_GRADIENT_CORRECTION_FRESH_DELTA_MODE="${LOCAL_GRADIENT_CORRECTION_FRESH_DELTA_MODE}" \
      LOCAL_GRADIENT_CORRECTION_FRESH_BUDGET_FRACTION="${LOCAL_GRADIENT_CORRECTION_FRESH_BUDGET_FRACTION}" \
      LOCAL_GRADIENT_CORRECTION_FRESH_MAX_POSES_PER_RECEIVER="${LOCAL_GRADIENT_CORRECTION_FRESH_MAX_POSES_PER_RECEIVER}" \
      LOCAL_GRADIENT_CORRECTION_INNER_ROUNDS="${LOCAL_GRADIENT_CORRECTION_INNER_ROUNDS}" \
      LOCAL_GRADIENT_CORRECTION_MAX_ROUNDS="${LOCAL_GRADIENT_CORRECTION_MAX_ROUNDS}" \
      POST_EXCHANGE_PERIOD="${POST_EXCHANGE_PERIOD}" \
      POST_EXCHANGE_MIN_POSE_DELTA="${POST_EXCHANGE_MIN_POSE_DELTA}" \
      POST_EXCHANGE_DELTA_MODE="${POST_EXCHANGE_DELTA_MODE}" \
      POST_EXCHANGE_BUDGET_FRACTION="${POST_EXCHANGE_BUDGET_FRACTION}" \
      POST_EXCHANGE_MAX_POSES_PER_RECEIVER="${POST_EXCHANGE_MAX_POSES_PER_RECEIVER}" \
      SYNC_AMM_REFERENCE_AFTER_LOCAL_GRADIENT_CORRECTION="${SYNC_AMM_REFERENCE_AFTER_LOCAL_GRADIENT_CORRECTION}" \
      GLOBAL_GRADIENT_CORRECTION="${GLOBAL_GRADIENT_CORRECTION}" \
      GLOBAL_GRADIENT_CORRECTION_STEP="${GLOBAL_GRADIENT_CORRECTION_STEP}" \
      GLOBAL_GRADIENT_CORRECTION_STEPS="${GLOBAL_GRADIENT_CORRECTION_STEPS}" \
      RESET_LOCAL_HISTORY_AFTER_GLOBAL_CORRECTION="${RESET_LOCAL_HISTORY_AFTER_GLOBAL_CORRECTION}" \
      SYNC_AMM_REFERENCE_AFTER_GLOBAL_CORRECTION="${SYNC_AMM_REFERENCE_AFTER_GLOBAL_CORRECTION}" \
      AMM_DPGO_SURROGATE_PARITY="${AMM_DPGO_SURROGATE_PARITY}" \
      AMM_DPGO_RECURSIVE_SIMPLE_STATE="${AMM_DPGO_RECURSIVE_SIMPLE_STATE}" \
      AMM_RECURSIVE_SIMPLE_REANCHOR_PERIOD="${AMM_RECURSIVE_SIMPLE_REANCHOR_PERIOD}" \
      AMM_DPGO_STRICT_REFINED_GATE="${AMM_DPGO_STRICT_REFINED_GATE}" \
      AMM_DPGO_RECOVER_TRANSLATIONS_AFTER_PROXIMAL="${AMM_DPGO_RECOVER_TRANSLATIONS_AFTER_PROXIMAL}" \
      AMM_DPGO_REFINED_STARTS_AT_RECOVERED_PROXIMAL="${AMM_DPGO_REFINED_STARTS_AT_RECOVERED_PROXIMAL}" \
      AMM_DPGO_MIXED_SURROGATE_PORTFOLIO="${AMM_DPGO_MIXED_SURROGATE_PORTFOLIO}" \
      AMM_MIXED_SURROGATE_SKIP_SIMPLE_AFTER_TRUE_LOCAL_STREAK="${AMM_MIXED_SURROGATE_SKIP_SIMPLE_AFTER_TRUE_LOCAL_STREAK}" \
      AMM_MIXED_SURROGATE_FORCE_SIMPLE_EVERY_SKIPPED_ROUNDS="${AMM_MIXED_SURROGATE_FORCE_SIMPLE_EVERY_SKIPPED_ROUNDS}" \
      TRACE_AMM="${TRACE_AMM}" \
      OUT_ROOT="${OUT_ROOT}/manual_reduced/${dataset}" \
      ./scripts/run_manual_dpgo_mm_six.sh
  done
  exit 0
fi

mkdir -p "${OUT_ROOT}"
printf 'dataset,updates,variant,status,global_cost,gradient,total_comm_mb,wall_time_sec,solver_time_per_node_sec,run_root,summary_csv\n' > "${COMPARISON_CSV}"

for dataset in "${DATASET_ORDER[@]}"; do
  echo "=== Compare manual DPGO-MM replay on ${dataset}, updates=${MAX_UPDATES} ==="

  dpgo_mm_mm_root="${OUT_ROOT}/dpgo_mm_mm/${dataset}"
  env -u BIN "${dpgo_mm_bin_env[@]}" \
    DATASETS="${dataset}" NUM_ROBOTS="${NUM_ROBOTS}" \
    MAX_ITERS="$((MAX_UPDATES + 1))" SCHEME=mm ACCELERATED=false \
    DIST_INIT="${DIST_INIT}" LOCAL_MAX_ITERATIONS="${LOCAL_MAX_ITERATIONS}" \
    LOCAL_MAX_ITERATIONS_ACCEPTED="${LOCAL_MAX_ITERATIONS_ACCEPTED}" \
    LOCAL_MAX_TCG_ITERATIONS="${DPGO_MM_LOCAL_MAX_TCG_ITERATIONS}" \
    AMM_TRACE="${DPGO_MM_AMM_TRACE}" \
    OUT_ROOT="${dpgo_mm_mm_root}" \
    "${ROOT_DIR}/scripts/run_dpgo_mm_six.sh"
  append_summary_row "${dataset}" "${MAX_UPDATES}" "dpgo_mm_mm" \
    "${dpgo_mm_mm_root}"

  dpgo_mm_amm_root="${OUT_ROOT}/dpgo_mm_amm/${dataset}"
  env -u BIN "${dpgo_mm_bin_env[@]}" \
    DATASETS="${dataset}" NUM_ROBOTS="${NUM_ROBOTS}" \
    MAX_ITERS="$((MAX_UPDATES + 1))" SCHEME=amm ACCELERATED=true \
    DIST_INIT="${DIST_INIT}" LOCAL_MAX_ITERATIONS="${LOCAL_MAX_ITERATIONS}" \
    LOCAL_MAX_ITERATIONS_ACCEPTED="${LOCAL_MAX_ITERATIONS_ACCEPTED}" \
    LOCAL_MAX_TCG_ITERATIONS="${DPGO_MM_LOCAL_MAX_TCG_ITERATIONS}" \
    AMM_TRACE="${DPGO_MM_AMM_TRACE}" \
    OUT_ROOT="${dpgo_mm_amm_root}" \
    "${ROOT_DIR}/scripts/run_dpgo_mm_six.sh"
  append_summary_row "${dataset}" "${MAX_UPDATES}" "dpgo_mm_amm" \
    "${dpgo_mm_amm_root}"

  manual_root="${OUT_ROOT}/manual_reduced/${dataset}"
  env "${manual_bin_env[@]}" \
    DATASETS="${dataset}" NUM_ROBOTS="${NUM_ROBOTS}" \
    MAX_ITERS="${MAX_UPDATES}" SCHEME="${MANUAL_SCHEME}" \
    ACCELERATED="${MANUAL_ACCELERATED}" LOCAL_SOLVER="${LOCAL_SOLVER}" \
    REDUCED_ROTATION_PRECONDITIONER="${REDUCED_ROTATION_PRECONDITIONER}" \
    LOCAL_MAX_ITERATIONS="${LOCAL_MAX_ITERATIONS}" \
    LOCAL_MAX_ITERATIONS_ACCEPTED="${LOCAL_MAX_ITERATIONS_ACCEPTED}" \
    LOCAL_MAX_TCG_ITERATIONS="${LOCAL_MAX_TCG_ITERATIONS}" \
    ADAPTIVE_REDUCED_TCG="${ADAPTIVE_REDUCED_TCG}" \
    ADAPTIVE_REDUCED_TCG_MAX_ITERATIONS="${ADAPTIVE_REDUCED_TCG_MAX_ITERATIONS}" \
    ADAPTIVE_REDUCED_TCG_GRADIENT_RATIO="${ADAPTIVE_REDUCED_TCG_GRADIENT_RATIO}" \
    REDUCED_ROTATION_TCG_RELATIVE_TOLERANCE="${REDUCED_ROTATION_TCG_RELATIVE_TOLERANCE}" \
    LOCAL_STATE_EXTRAPOLATION="${LOCAL_STATE_EXTRAPOLATION}" \
    LOCAL_STATE_EXTRAPOLATION_GAMMA="${LOCAL_STATE_EXTRAPOLATION_GAMMA}" \
    LOCAL_STATE_EXTRAPOLATION_GAMMAS="${LOCAL_STATE_EXTRAPOLATION_GAMMAS}" \
    LOCAL_MODEL_G_EXTRAPOLATION="${LOCAL_MODEL_G_EXTRAPOLATION}" \
    LOCAL_MODEL_G_EXTRAPOLATION_GAMMA="${LOCAL_MODEL_G_EXTRAPOLATION_GAMMA}" \
    LOCAL_MODEL_G_EXTRAPOLATION_GAMMAS="${LOCAL_MODEL_G_EXTRAPOLATION_GAMMAS}" \
    COUPLED_STATE_G_EXTRAPOLATION="${COUPLED_STATE_G_EXTRAPOLATION}" \
    COUPLED_STATE_G_EXTRAPOLATION_GAMMA="${COUPLED_STATE_G_EXTRAPOLATION_GAMMA}" \
    COUPLED_STATE_G_EXTRAPOLATION_GAMMAS="${COUPLED_STATE_G_EXTRAPOLATION_GAMMAS}" \
    LOCAL_ANDERSON_ACCELERATION="${LOCAL_ANDERSON_ACCELERATION}" \
    LOCAL_ANDERSON_MAX_ALPHA="${LOCAL_ANDERSON_MAX_ALPHA}" \
    LOCAL_CANDIDATE_COST_TIE_TOLERANCE="${LOCAL_CANDIDATE_COST_TIE_TOLERANCE}" \
    GLOBAL_STATE_EXTRAPOLATION="${GLOBAL_STATE_EXTRAPOLATION}" \
    GLOBAL_STATE_EXTRAPOLATION_GAMMA="${GLOBAL_STATE_EXTRAPOLATION_GAMMA}" \
    GLOBAL_STATE_EXTRAPOLATION_GAMMAS="${GLOBAL_STATE_EXTRAPOLATION_GAMMAS}" \
    GLOBAL_ANDERSON_ACCELERATION="${GLOBAL_ANDERSON_ACCELERATION}" \
    GLOBAL_ANDERSON_MAX_ALPHA="${GLOBAL_ANDERSON_MAX_ALPHA}" \
    LOCAL_GRADIENT_CORRECTION="${LOCAL_GRADIENT_CORRECTION}" \
    LOCAL_GRADIENT_CORRECTION_STEP="${LOCAL_GRADIENT_CORRECTION_STEP}" \
    LOCAL_GRADIENT_CORRECTION_STEPS="${LOCAL_GRADIENT_CORRECTION_STEPS}" \
      LOCAL_GRADIENT_CORRECTION_SHARED_STEP="${LOCAL_GRADIENT_CORRECTION_SHARED_STEP}" \
      LOCAL_GRADIENT_CORRECTION_NEIGHBORHOOD_STEP="${LOCAL_GRADIENT_CORRECTION_NEIGHBORHOOD_STEP}" \
      LOCAL_GRADIENT_CORRECTION_CURVATURE_STEP="${LOCAL_GRADIENT_CORRECTION_CURVATURE_STEP}" \
      LOCAL_GRADIENT_CORRECTION_COUPLED_DIRECTION="${LOCAL_GRADIENT_CORRECTION_COUPLED_DIRECTION}" \
      LOCAL_GRADIENT_CORRECTION_COUPLED_DIRECTION_BUDGET_FRACTION="${LOCAL_GRADIENT_CORRECTION_COUPLED_DIRECTION_BUDGET_FRACTION}" \
      LOCAL_GRADIENT_CORRECTION_COUPLED_DIRECTION_MAX_PACKETS_PER_RECEIVER="${LOCAL_GRADIENT_CORRECTION_COUPLED_DIRECTION_MAX_PACKETS_PER_RECEIVER}" \
      LOCAL_GRADIENT_CORRECTION_COUPLED_DIRECTION_TOPK_ENTRIES="${LOCAL_GRADIENT_CORRECTION_COUPLED_DIRECTION_TOPK_ENTRIES}" \
      LOCAL_GRADIENT_CORRECTION_COUPLED_DIRECTION_MIN_SCORE="${LOCAL_GRADIENT_CORRECTION_COUPLED_DIRECTION_MIN_SCORE}" \
      LOCAL_GRADIENT_CORRECTION_COUPLED_DIRECTION_MIN_SCORE_RATIO="${LOCAL_GRADIENT_CORRECTION_COUPLED_DIRECTION_MIN_SCORE_RATIO}" \
      LOCAL_GRADIENT_CORRECTION_COUPLED_DIRECTION_BYTE_BUDGET_MB="${LOCAL_GRADIENT_CORRECTION_COUPLED_DIRECTION_BYTE_BUDGET_MB}" \
      LOCAL_GRADIENT_CORRECTION_BOUNDARY_ONLY="${LOCAL_GRADIENT_CORRECTION_BOUNDARY_ONLY}" \
      LOCAL_GRADIENT_CORRECTION_BLOCK_JACOBI="${LOCAL_GRADIENT_CORRECTION_BLOCK_JACOBI}" \
      LOCAL_GRADIENT_CORRECTION_COMPACT_SCHUR="${LOCAL_GRADIENT_CORRECTION_COMPACT_SCHUR}" \
      LOCAL_GRADIENT_CORRECTION_COMPACT_SCHUR_MAX_BOUNDARY_POSES="${LOCAL_GRADIENT_CORRECTION_COMPACT_SCHUR_MAX_BOUNDARY_POSES}" \
      LOCAL_GRADIENT_CORRECTION_COMPACT_SCHUR_MAX_PRIVATE_COLS="${LOCAL_GRADIENT_CORRECTION_COMPACT_SCHUR_MAX_PRIVATE_COLS}" \
      LOCAL_GRADIENT_CORRECTION_COMPACT_SCHUR_DAMPING="${LOCAL_GRADIENT_CORRECTION_COMPACT_SCHUR_DAMPING}" \
      LOCAL_GRADIENT_CORRECTION_COMPACT_SCHUR_GRADIENT_GUARD="${LOCAL_GRADIENT_CORRECTION_COMPACT_SCHUR_GRADIENT_GUARD}" \
      LOCAL_GRADIENT_CORRECTION_COMPACT_SCHUR_MAX_GRADIENT_INCREASE_RATIO="${LOCAL_GRADIENT_CORRECTION_COMPACT_SCHUR_MAX_GRADIENT_INCREASE_RATIO}" \
      LOCAL_GRADIENT_CORRECTION_FRESH_NEIGHBOR_EXCHANGE="${LOCAL_GRADIENT_CORRECTION_FRESH_NEIGHBOR_EXCHANGE}" \
      LOCAL_GRADIENT_CORRECTION_FRESH_MIN_POSE_DELTA="${LOCAL_GRADIENT_CORRECTION_FRESH_MIN_POSE_DELTA}" \
      LOCAL_GRADIENT_CORRECTION_FRESH_DELTA_MODE="${LOCAL_GRADIENT_CORRECTION_FRESH_DELTA_MODE}" \
      LOCAL_GRADIENT_CORRECTION_FRESH_BUDGET_FRACTION="${LOCAL_GRADIENT_CORRECTION_FRESH_BUDGET_FRACTION}" \
      LOCAL_GRADIENT_CORRECTION_FRESH_MAX_POSES_PER_RECEIVER="${LOCAL_GRADIENT_CORRECTION_FRESH_MAX_POSES_PER_RECEIVER}" \
    LOCAL_GRADIENT_CORRECTION_INNER_ROUNDS="${LOCAL_GRADIENT_CORRECTION_INNER_ROUNDS}" \
    LOCAL_GRADIENT_CORRECTION_MAX_ROUNDS="${LOCAL_GRADIENT_CORRECTION_MAX_ROUNDS}" \
    POST_EXCHANGE_PERIOD="${POST_EXCHANGE_PERIOD}" \
    POST_EXCHANGE_MIN_POSE_DELTA="${POST_EXCHANGE_MIN_POSE_DELTA}" \
    POST_EXCHANGE_DELTA_MODE="${POST_EXCHANGE_DELTA_MODE}" \
    POST_EXCHANGE_BUDGET_FRACTION="${POST_EXCHANGE_BUDGET_FRACTION}" \
    POST_EXCHANGE_MAX_POSES_PER_RECEIVER="${POST_EXCHANGE_MAX_POSES_PER_RECEIVER}" \
    SYNC_AMM_REFERENCE_AFTER_LOCAL_GRADIENT_CORRECTION="${SYNC_AMM_REFERENCE_AFTER_LOCAL_GRADIENT_CORRECTION}" \
    GLOBAL_GRADIENT_CORRECTION="${GLOBAL_GRADIENT_CORRECTION}" \
    GLOBAL_GRADIENT_CORRECTION_STEP="${GLOBAL_GRADIENT_CORRECTION_STEP}" \
    GLOBAL_GRADIENT_CORRECTION_STEPS="${GLOBAL_GRADIENT_CORRECTION_STEPS}" \
    RESET_LOCAL_HISTORY_AFTER_GLOBAL_CORRECTION="${RESET_LOCAL_HISTORY_AFTER_GLOBAL_CORRECTION}" \
    SYNC_AMM_REFERENCE_AFTER_GLOBAL_CORRECTION="${SYNC_AMM_REFERENCE_AFTER_GLOBAL_CORRECTION}" \
    AMM_DPGO_SURROGATE_PARITY="${AMM_DPGO_SURROGATE_PARITY}" \
    AMM_DPGO_RECURSIVE_SIMPLE_STATE="${AMM_DPGO_RECURSIVE_SIMPLE_STATE}" \
    AMM_RECURSIVE_SIMPLE_REANCHOR_PERIOD="${AMM_RECURSIVE_SIMPLE_REANCHOR_PERIOD}" \
    AMM_DPGO_STRICT_REFINED_GATE="${AMM_DPGO_STRICT_REFINED_GATE}" \
    AMM_DPGO_RECOVER_TRANSLATIONS_AFTER_PROXIMAL="${AMM_DPGO_RECOVER_TRANSLATIONS_AFTER_PROXIMAL}" \
    AMM_DPGO_REFINED_STARTS_AT_RECOVERED_PROXIMAL="${AMM_DPGO_REFINED_STARTS_AT_RECOVERED_PROXIMAL}" \
    AMM_DPGO_MIXED_SURROGATE_PORTFOLIO="${AMM_DPGO_MIXED_SURROGATE_PORTFOLIO}" \
    AMM_MIXED_SURROGATE_SKIP_SIMPLE_AFTER_TRUE_LOCAL_STREAK="${AMM_MIXED_SURROGATE_SKIP_SIMPLE_AFTER_TRUE_LOCAL_STREAK}" \
    AMM_MIXED_SURROGATE_FORCE_SIMPLE_EVERY_SKIPPED_ROUNDS="${AMM_MIXED_SURROGATE_FORCE_SIMPLE_EVERY_SKIPPED_ROUNDS}" \
    TRACE_AMM="${TRACE_AMM}" \
    OUT_ROOT="${manual_root}" \
    "${ROOT_DIR}/scripts/run_manual_dpgo_mm_six.sh"
  append_summary_row "${dataset}" "${MAX_UPDATES}" "manual_reduced" \
    "${manual_root}"
done

write_pairwise_table

echo "Saved comparison: ${COMPARISON_CSV}"
echo "Saved pairwise deltas: ${PAIRWISE_CSV}"
