#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Local robot solves can be parallelized at the process level. Keep nested
# dense/sparse linear algebra libraries single-threaded by default to avoid
# oversubscription on one-machine benchmark runs.
export OMP_NUM_THREADS="${OMP_NUM_THREADS:-1}"
export OPENBLAS_NUM_THREADS="${OPENBLAS_NUM_THREADS:-1}"
export MKL_NUM_THREADS="${MKL_NUM_THREADS:-1}"
export BLIS_NUM_THREADS="${BLIS_NUM_THREADS:-1}"
export VECLIB_MAXIMUM_THREADS="${VECLIB_MAXIMUM_THREADS:-1}"
export NUMEXPR_NUM_THREADS="${NUMEXPR_NUM_THREADS:-1}"

BIN_DEFAULT="${ROOT_DIR}/build/bin/manual-dpgo-mm-example"
BIN="${BIN:-${BIN_DEFAULT}}"
NUM_ROBOTS="${NUM_ROBOTS:-5}"
MAX_ITERS="${MAX_ITERS:-20}"
SCHEME="${SCHEME:-mm}"
ACCELERATED="${ACCELERATED:-false}"
DIST_INIT="${DIST_INIT:-false}"
DIST_INIT_REFINEMENT_ROUNDS="${DIST_INIT_REFINEMENT_ROUNDS:-4}"
DIST_INIT_FIXED_NEIGHBOR_CHORDAL_REFIT="${DIST_INIT_FIXED_NEIGHBOR_CHORDAL_REFIT:-false}"
EXTERNAL_INITIAL_ESTIMATE="${EXTERNAL_INITIAL_ESTIMATE:-}"
EXTERNAL_INITIAL_ESTIMATE_DIR="${EXTERNAL_INITIAL_ESTIMATE_DIR:-}"
LOCAL_SOLVER="${LOCAL_SOLVER:-manual_full}"
REDUCED_ROTATION_PRECONDITIONER="${REDUCED_ROTATION_PRECONDITIONER:-none}"
REDUCED_SURROGATE_MODE="${REDUCED_SURROGATE_MODE:-true_local}"
SURROGATE_MODE="${SURROGATE_MODE:-legacy}"
EDGE_SPLIT_THETA_MODE="${EDGE_SPLIT_THETA_MODE:-constant}"
EDGE_SPLIT_THETA_DEFAULT="${EDGE_SPLIT_THETA_DEFAULT:-0.5}"
EDGE_SPLIT_THETA_MIN="${EDGE_SPLIT_THETA_MIN:-0.15}"
EDGE_SPLIT_THETA_MAX="${EDGE_SPLIT_THETA_MAX:-0.85}"
EDGE_SPLIT_THETA_CANDIDATES="${EDGE_SPLIT_THETA_CANDIDATES:-0.2,0.35,0.5,0.65,0.8}"
MM_ACCELERATOR="${MM_ACCELERATOR:-nesterov_legacy}"
MM_SAFEGUARD="${MM_SAFEGUARD:-local_surrogate}"
DEBUG_SURROGATE_BOUND_CHECK="${DEBUG_SURROGATE_BOUND_CHECK:-false}"
DEBUG_SURROGATE_BOUND_SAMPLES="${DEBUG_SURROGATE_BOUND_SAMPLES:-8}"
FEH_LINEAR_BACKEND="${FEH_LINEAR_BACKEND:-manual_full_rtr}"
FEH_SCHUR_WARM_START="${FEH_SCHUR_WARM_START:-false}"
FEH_FINAL_POLISH_RTR="${FEH_FINAL_POLISH_RTR:-false}"
FEH_SCHUR_DAMPING="${FEH_SCHUR_DAMPING:-1e-6}"
FEH_LINEAR_REL_TOL="${FEH_LINEAR_REL_TOL:-1e-6}"
FEH_LINEAR_ABS_TOL="${FEH_LINEAR_ABS_TOL:-1e-10}"
FEH_LINEAR_MAX_ITERS="${FEH_LINEAR_MAX_ITERS:-200}"
FEH_LINEAR_BLOCK_JACOBI="${FEH_LINEAR_BLOCK_JACOBI:-true}"
FEH_SPARSE_MATVEC="${FEH_SPARSE_MATVEC:-true}"
FEH_PRECOND_TRANSLATION_SCHUR="${FEH_PRECOND_TRANSLATION_SCHUR:-false}"
FEH_PRECOND_LOCAL_CHAIN="${FEH_PRECOND_LOCAL_CHAIN:-false}"
FEH_PRECOND_TRANSLATION_BLOCK="${FEH_PRECOND_TRANSLATION_BLOCK:-false}"
FEH_PRECOND_TRANSLATION_SPARSE_SCHUR="${FEH_PRECOND_TRANSLATION_SPARSE_SCHUR:-false}"
FEH_PRECOND_TRANSLATION_LOCAL_SCHUR="${FEH_PRECOND_TRANSLATION_LOCAL_SCHUR:-false}"
FEH_PRECOND_TRANSLATION_LOCAL_SCHUR_MAX_POSES="${FEH_PRECOND_TRANSLATION_LOCAL_SCHUR_MAX_POSES:-32}"
FEH_PRECOND_LAPLACIAN_DEFLATION="${FEH_PRECOND_LAPLACIAN_DEFLATION:-false}"
FEH_PRECOND_LAPLACIAN_DEFLATION_BASIS_SIZE="${FEH_PRECOND_LAPLACIAN_DEFLATION_BASIS_SIZE:-4}"
FEH_PRECOND_LAPLACIAN_DEFLATION_MAX_EIGEN_POSES="${FEH_PRECOND_LAPLACIAN_DEFLATION_MAX_EIGEN_POSES:-512}"
FEH_PRECOND_REDUCED_ROTATION="${FEH_PRECOND_REDUCED_ROTATION:-false}"
FEH_REDUCED_ROTATION_INITIAL_GUESS="${FEH_REDUCED_ROTATION_INITIAL_GUESS:-false}"
FEH_TRANSLATION_RECOVERY_INITIAL_GUESS="${FEH_TRANSLATION_RECOVERY_INITIAL_GUESS:-false}"
FEH_RQN_WARM_START="${FEH_RQN_WARM_START:-false}"
FEH_PRECOND_RQN_MEMORY="${FEH_PRECOND_RQN_MEMORY:-false}"
FEH_RQN_MEMORY_SIZE="${FEH_RQN_MEMORY_SIZE:-5}"
FEH_RQN_MIN_CURVATURE_RATIO="${FEH_RQN_MIN_CURVATURE_RATIO:-1e-8}"
FEH_WARM_START_MAX_NORM="${FEH_WARM_START_MAX_NORM:-1}"
FEH_WARM_START_BACKTRACKING_STEPS="${FEH_WARM_START_BACKTRACKING_STEPS:-4}"
FEH_SELECT_BEST_BACKTRACKING="${FEH_SELECT_BEST_BACKTRACKING:-false}"
FEH_STEP_PARETO_SELECTOR="${FEH_STEP_PARETO_SELECTOR:-false}"
FEH_STEP_PARETO_MIN_DECREASE_RATIO="${FEH_STEP_PARETO_MIN_DECREASE_RATIO:-0.9}"
FEH_BACKTRACKING_SHARED_POSE_PROX_WEIGHT="${FEH_BACKTRACKING_SHARED_POSE_PROX_WEIGHT:-0}"
FEH_PROJECTED_MODEL_RHO_GUARD="${FEH_PROJECTED_MODEL_RHO_GUARD:-false}"
FEH_PROJECTED_MODEL_RHO_ETA="${FEH_PROJECTED_MODEL_RHO_ETA:-1e-4}"
FEH_ACTIVE_SEPARATOR_CORRECTION="${FEH_ACTIVE_SEPARATOR_CORRECTION:-false}"
FEH_ACTIVE_SEPARATOR_STEP_CAP="${FEH_ACTIVE_SEPARATOR_STEP_CAP:-5e-2}"
FEH_ACTIVE_SEPARATOR_BLOCK_JACOBI="${FEH_ACTIVE_SEPARATOR_BLOCK_JACOBI:-false}"
FEH_ACTIVE_SEPARATOR_COMPACT_SCHUR="${FEH_ACTIVE_SEPARATOR_COMPACT_SCHUR:-false}"
FEH_ACTIVE_SEPARATOR_LM_SCHUR="${FEH_ACTIVE_SEPARATOR_LM_SCHUR:-false}"
FEH_ACTIVE_SEPARATOR_LM_SCHUR_MAX_BOUNDARY_POSES="${FEH_ACTIVE_SEPARATOR_LM_SCHUR_MAX_BOUNDARY_POSES:-32}"
FEH_ACTIVE_SEPARATOR_LM_SCHUR_MAX_PRIVATE_COLS="${FEH_ACTIVE_SEPARATOR_LM_SCHUR_MAX_PRIVATE_COLS:-64}"
FEH_ACTIVE_SEPARATOR_LM_SCHUR_DAMPING="${FEH_ACTIVE_SEPARATOR_LM_SCHUR_DAMPING:-1e-6}"
FEH_ACTIVE_SEPARATOR_LM_SCHUR_BACKTRACKING_STEPS="${FEH_ACTIVE_SEPARATOR_LM_SCHUR_BACKTRACKING_STEPS:-4}"
FEH_ACTIVE_SEPARATOR_LM_SCHUR_MIN_COST_IMPROVEMENT="${FEH_ACTIVE_SEPARATOR_LM_SCHUR_MIN_COST_IMPROVEMENT:-0}"
FEH_ACTIVE_SEPARATOR_LM_SCHUR_MAX_ROUNDS="${FEH_ACTIVE_SEPARATOR_LM_SCHUR_MAX_ROUNDS:-0}"
FEH_ACTIVE_SEPARATOR_LM_SCHUR_SCORE_MODE="${FEH_ACTIVE_SEPARATOR_LM_SCHUR_SCORE_MODE:-gradient}"
FEH_ACTIVE_SEPARATOR_LM_SCHUR_GRADIENT_GUARD="${FEH_ACTIVE_SEPARATOR_LM_SCHUR_GRADIENT_GUARD:-false}"
FEH_ACTIVE_SEPARATOR_LM_SCHUR_MAX_GRADIENT_INCREASE_RATIO="${FEH_ACTIVE_SEPARATOR_LM_SCHUR_MAX_GRADIENT_INCREASE_RATIO:-0}"
FEH_TRANSLATION_RECOVERY_POLISH="${FEH_TRANSLATION_RECOVERY_POLISH:-false}"
FEH_TRANSLATION_RECOVERY_POLISH_GRADIENT_GUARD="${FEH_TRANSLATION_RECOVERY_POLISH_GRADIENT_GUARD:-false}"
FEH_TRANSLATION_RECOVERY_POLISH_MAX_GRADIENT_INCREASE_RATIO="${FEH_TRANSLATION_RECOVERY_POLISH_MAX_GRADIENT_INCREASE_RATIO:-0}"
FEH_TRANSLATION_RECOVERY_POLISH_BACKTRACKING="${FEH_TRANSLATION_RECOVERY_POLISH_BACKTRACKING:-false}"
FEH_TRANSLATION_RECOVERY_POLISH_BACKTRACKING_STEPS="${FEH_TRANSLATION_RECOVERY_POLISH_BACKTRACKING_STEPS:-4}"
FEH_TRANSLATION_RECOVERY_POLISH_MERIT_SELECTOR="${FEH_TRANSLATION_RECOVERY_POLISH_MERIT_SELECTOR:-false}"
FEH_TRANSLATION_RECOVERY_POLISH_MERIT_MIN_COST_RECOVERY_RATIO="${FEH_TRANSLATION_RECOVERY_POLISH_MERIT_MIN_COST_RECOVERY_RATIO:-0.9}"
FEH_TRANSLATION_RECOVERY_POLISH_SELECTED_ONLY="${FEH_TRANSLATION_RECOVERY_POLISH_SELECTED_ONLY:-false}"
FEH_TRANSLATION_RECOVERY_STEP_TRIALS="${FEH_TRANSLATION_RECOVERY_STEP_TRIALS:-false}"
FEH_LOCAL_PORTFOLIO="${FEH_LOCAL_PORTFOLIO:-false}"
MANUAL_FULL_PORTFOLIO="${MANUAL_FULL_PORTFOLIO:-false}"
FEH_SCHWARZ_PRESMOOTHING="${FEH_SCHWARZ_PRESMOOTHING:-false}"
FEH_SCHWARZ_SWEEPS="${FEH_SCHWARZ_SWEEPS:-1}"
FEH_SCHWARZ_MAX_BLOCK_NORM="${FEH_SCHWARZ_MAX_BLOCK_NORM:-0.25}"
FEH_SCHWARZ_BLOCK_MODE="${FEH_SCHWARZ_BLOCK_MODE:-per_pose}"
LOCAL_MAX_ITERATIONS="${LOCAL_MAX_ITERATIONS:-1}"
LOCAL_MAX_ITERATIONS_ACCEPTED="${LOCAL_MAX_ITERATIONS_ACCEPTED:-1}"
if [[ -z "${LOCAL_MAX_TCG_ITERATIONS+x}" ]]; then
  local_solver_default_key="${LOCAL_SOLVER,,}"
  if [[ "${local_solver_default_key}" == "reduced_rotation" || "${local_solver_default_key}" == "translation_eliminated" ]]; then
    LOCAL_MAX_TCG_ITERATIONS="10"
  else
    LOCAL_MAX_TCG_ITERATIONS="50"
  fi
fi
LOCAL_GRAD_NORM_TOL="${LOCAL_GRAD_NORM_TOL:-1e-3}"
RECORD_LOCAL_MODEL_DIAGNOSTICS="${RECORD_LOCAL_MODEL_DIAGNOSTICS:-false}"
PARALLEL_LOCAL_SOLVES="${PARALLEL_LOCAL_SOLVES:-true}"
ADAPTIVE_REDUCED_TCG="${ADAPTIVE_REDUCED_TCG:-false}"
ADAPTIVE_REDUCED_TCG_MAX_ITERATIONS="${ADAPTIVE_REDUCED_TCG_MAX_ITERATIONS:-50}"
ADAPTIVE_REDUCED_TCG_GRADIENT_RATIO="${ADAPTIVE_REDUCED_TCG_GRADIENT_RATIO:-0.15}"
REDUCED_ROTATION_TCG_RELATIVE_TOLERANCE="${REDUCED_ROTATION_TCG_RELATIVE_TOLERANCE:-0.1}"
LOCAL_STATE_EXTRAPOLATION="${LOCAL_STATE_EXTRAPOLATION:-false}"
LOCAL_STATE_EXTRAPOLATION_GAMMA="${LOCAL_STATE_EXTRAPOLATION_GAMMA:-0.5}"
LOCAL_STATE_EXTRAPOLATION_GAMMAS="${LOCAL_STATE_EXTRAPOLATION_GAMMAS:-}"
LOCAL_STATE_EXTRAPOLATION_USE_ACTIVE_SURROGATE="${LOCAL_STATE_EXTRAPOLATION_USE_ACTIVE_SURROGATE:-false}"
LOCAL_BOUNDARY_PROXIMAL_CANDIDATE="${LOCAL_BOUNDARY_PROXIMAL_CANDIDATE:-false}"
LOCAL_BOUNDARY_PROXIMAL_WEIGHT="${LOCAL_BOUNDARY_PROXIMAL_WEIGHT:-0.1}"
LOCAL_BOUNDARY_PROXIMAL_WEIGHTS="${LOCAL_BOUNDARY_PROXIMAL_WEIGHTS:-}"
LOCAL_MODEL_G_EXTRAPOLATION="${LOCAL_MODEL_G_EXTRAPOLATION:-false}"
LOCAL_MODEL_G_EXTRAPOLATION_GAMMA="${LOCAL_MODEL_G_EXTRAPOLATION_GAMMA:-0.5}"
LOCAL_MODEL_G_EXTRAPOLATION_GAMMAS="${LOCAL_MODEL_G_EXTRAPOLATION_GAMMAS:-}"
COUPLED_STATE_G_EXTRAPOLATION="${COUPLED_STATE_G_EXTRAPOLATION:-false}"
COUPLED_STATE_G_EXTRAPOLATION_GAMMA="${COUPLED_STATE_G_EXTRAPOLATION_GAMMA:-0.5}"
COUPLED_STATE_G_EXTRAPOLATION_GAMMAS="${COUPLED_STATE_G_EXTRAPOLATION_GAMMAS:-}"
LOCAL_ANDERSON_ACCELERATION="${LOCAL_ANDERSON_ACCELERATION:-false}"
LOCAL_ANDERSON_MAX_ALPHA="${LOCAL_ANDERSON_MAX_ALPHA:-1}"
LOCAL_SQUAREM_MAX_ALPHA="${LOCAL_SQUAREM_MAX_ALPHA:-10}"
LOCAL_CANDIDATE_COST_TIE_TOLERANCE="${LOCAL_CANDIDATE_COST_TIE_TOLERANCE:-0}"
GLOBAL_STATE_EXTRAPOLATION="${GLOBAL_STATE_EXTRAPOLATION:-false}"
GLOBAL_STATE_EXTRAPOLATION_GAMMA="${GLOBAL_STATE_EXTRAPOLATION_GAMMA:-0.5}"
GLOBAL_STATE_EXTRAPOLATION_GAMMAS="${GLOBAL_STATE_EXTRAPOLATION_GAMMAS:-}"
GLOBAL_ANDERSON_ACCELERATION="${GLOBAL_ANDERSON_ACCELERATION:-false}"
GLOBAL_ANDERSON_MAX_ALPHA="${GLOBAL_ANDERSON_MAX_ALPHA:-1}"
LOCAL_GRADIENT_CORRECTION="${LOCAL_GRADIENT_CORRECTION:-false}"
LOCAL_GRADIENT_CORRECTION_STEP="${LOCAL_GRADIENT_CORRECTION_STEP:-1e-3}"
LOCAL_GRADIENT_CORRECTION_STEPS="${LOCAL_GRADIENT_CORRECTION_STEPS:-}"
LOCAL_GRADIENT_CORRECTION_SHARED_STEP="${LOCAL_GRADIENT_CORRECTION_SHARED_STEP:-false}"
LOCAL_GRADIENT_CORRECTION_NEIGHBORHOOD_STEP="${LOCAL_GRADIENT_CORRECTION_NEIGHBORHOOD_STEP:-false}"
LOCAL_GRADIENT_CORRECTION_CURVATURE_STEP="${LOCAL_GRADIENT_CORRECTION_CURVATURE_STEP:-false}"
LOCAL_GRADIENT_CORRECTION_COUPLED_DIRECTION="${LOCAL_GRADIENT_CORRECTION_COUPLED_DIRECTION:-false}"
LOCAL_GRADIENT_CORRECTION_COUPLED_DIRECTION_BUDGET_FRACTION="${LOCAL_GRADIENT_CORRECTION_COUPLED_DIRECTION_BUDGET_FRACTION:-1}"
LOCAL_GRADIENT_CORRECTION_COUPLED_DIRECTION_MAX_PACKETS_PER_RECEIVER="${LOCAL_GRADIENT_CORRECTION_COUPLED_DIRECTION_MAX_PACKETS_PER_RECEIVER:-0}"
LOCAL_GRADIENT_CORRECTION_COUPLED_DIRECTION_TOPK_ENTRIES="${LOCAL_GRADIENT_CORRECTION_COUPLED_DIRECTION_TOPK_ENTRIES:-0}"
LOCAL_GRADIENT_CORRECTION_COUPLED_DIRECTION_MIN_SCORE="${LOCAL_GRADIENT_CORRECTION_COUPLED_DIRECTION_MIN_SCORE:-0}"
LOCAL_GRADIENT_CORRECTION_COUPLED_DIRECTION_MIN_SCORE_RATIO="${LOCAL_GRADIENT_CORRECTION_COUPLED_DIRECTION_MIN_SCORE_RATIO:-0}"
LOCAL_GRADIENT_CORRECTION_COUPLED_DIRECTION_BYTE_BUDGET_MB="${LOCAL_GRADIENT_CORRECTION_COUPLED_DIRECTION_BYTE_BUDGET_MB:-0}"
LOCAL_GRADIENT_CORRECTION_BOUNDARY_ONLY="${LOCAL_GRADIENT_CORRECTION_BOUNDARY_ONLY:-false}"
LOCAL_GRADIENT_CORRECTION_BLOCK_JACOBI="${LOCAL_GRADIENT_CORRECTION_BLOCK_JACOBI:-false}"
LOCAL_GRADIENT_CORRECTION_COMPACT_SCHUR="${LOCAL_GRADIENT_CORRECTION_COMPACT_SCHUR:-false}"
LOCAL_GRADIENT_CORRECTION_COMPACT_SCHUR_MAX_BOUNDARY_POSES="${LOCAL_GRADIENT_CORRECTION_COMPACT_SCHUR_MAX_BOUNDARY_POSES:-32}"
LOCAL_GRADIENT_CORRECTION_COMPACT_SCHUR_MAX_PRIVATE_COLS="${LOCAL_GRADIENT_CORRECTION_COMPACT_SCHUR_MAX_PRIVATE_COLS:-64}"
LOCAL_GRADIENT_CORRECTION_COMPACT_SCHUR_DAMPING="${LOCAL_GRADIENT_CORRECTION_COMPACT_SCHUR_DAMPING:-1e-6}"
LOCAL_GRADIENT_CORRECTION_COMPACT_SCHUR_MIN_COST_DECREASE="${LOCAL_GRADIENT_CORRECTION_COMPACT_SCHUR_MIN_COST_DECREASE:-0}"
LOCAL_GRADIENT_CORRECTION_COMPACT_SCHUR_GRADIENT_GUARD="${LOCAL_GRADIENT_CORRECTION_COMPACT_SCHUR_GRADIENT_GUARD:-false}"
LOCAL_GRADIENT_CORRECTION_COMPACT_SCHUR_MAX_GRADIENT_INCREASE_RATIO="${LOCAL_GRADIENT_CORRECTION_COMPACT_SCHUR_MAX_GRADIENT_INCREASE_RATIO:-0}"
LOCAL_GRADIENT_CORRECTION_FRESH_NEIGHBOR_EXCHANGE="${LOCAL_GRADIENT_CORRECTION_FRESH_NEIGHBOR_EXCHANGE:-false}"
LOCAL_GRADIENT_CORRECTION_FRESH_MIN_POSE_DELTA="${LOCAL_GRADIENT_CORRECTION_FRESH_MIN_POSE_DELTA:-0}"
LOCAL_GRADIENT_CORRECTION_FRESH_DELTA_MODE="${LOCAL_GRADIENT_CORRECTION_FRESH_DELTA_MODE:-absolute}"
LOCAL_GRADIENT_CORRECTION_FRESH_BUDGET_FRACTION="${LOCAL_GRADIENT_CORRECTION_FRESH_BUDGET_FRACTION:-1}"
LOCAL_GRADIENT_CORRECTION_FRESH_MAX_POSES_PER_RECEIVER="${LOCAL_GRADIENT_CORRECTION_FRESH_MAX_POSES_PER_RECEIVER:-0}"
LOCAL_GRADIENT_CORRECTION_INNER_ROUNDS="${LOCAL_GRADIENT_CORRECTION_INNER_ROUNDS:-1}"
LOCAL_GRADIENT_CORRECTION_MAX_ROUNDS="${LOCAL_GRADIENT_CORRECTION_MAX_ROUNDS:-0}"
POST_EXCHANGE_PERIOD="${POST_EXCHANGE_PERIOD:-1}"
POST_EXCHANGE_MIN_POSE_DELTA="${POST_EXCHANGE_MIN_POSE_DELTA:-0}"
POST_EXCHANGE_DELTA_MODE="${POST_EXCHANGE_DELTA_MODE:-absolute}"
POST_EXCHANGE_BUDGET_FRACTION="${POST_EXCHANGE_BUDGET_FRACTION:-1}"
POST_EXCHANGE_MAX_POSES_PER_RECEIVER="${POST_EXCHANGE_MAX_POSES_PER_RECEIVER:-0}"
COMM_TOPOLOGY_FILE="${COMM_TOPOLOGY_FILE:-}"
COMM_TOPOLOGY_INITIAL_FULL="${COMM_TOPOLOGY_INITIAL_FULL:-true}"
COMM_TOPOLOGY_MAX_RELAY_HOPS="${COMM_TOPOLOGY_MAX_RELAY_HOPS:-0}"
COMM_TOPOLOGY_HOP_BUDGET_FRACTION="${COMM_TOPOLOGY_HOP_BUDGET_FRACTION:-1}"
COMM_TOPOLOGY_STALE_AWARE_RELAY_SCORE="${COMM_TOPOLOGY_STALE_AWARE_RELAY_SCORE:-false}"
COMM_TOPOLOGY_STALE_AWARE_RELAY_AGE_GAIN="${COMM_TOPOLOGY_STALE_AWARE_RELAY_AGE_GAIN:-1}"
COMM_TOPOLOGY_DELTA_COMPRESSION="${COMM_TOPOLOGY_DELTA_COMPRESSION:-false}"
COMM_TOPOLOGY_DELTA_MODE="${COMM_TOPOLOGY_DELTA_MODE:-sparse}"
COMM_TOPOLOGY_DELTA_TOPK="${COMM_TOPOLOGY_DELTA_TOPK:-4}"
COMM_TOPOLOGY_DELTA_MAX_RECONSTRUCTION_ERROR="${COMM_TOPOLOGY_DELTA_MAX_RECONSTRUCTION_ERROR:-0.0005}"
COMM_TOPOLOGY_LIFTED_DELTA_COMPRESSION="${COMM_TOPOLOGY_LIFTED_DELTA_COMPRESSION:-false}"
COMM_TOPOLOGY_LIFTED_DELTA_MAX_RECONSTRUCTION_ERROR="${COMM_TOPOLOGY_LIFTED_DELTA_MAX_RECONSTRUCTION_ERROR:-0.0005}"
COMM_TOPOLOGY_LIFTED_DELTA_RANK="${COMM_TOPOLOGY_LIFTED_DELTA_RANK:-2}"
COMM_TOPOLOGY_VALUE_SCHEDULER="${COMM_TOPOLOGY_VALUE_SCHEDULER:-false}"
COMM_TOPOLOGY_VALUE_SCHEDULER_MODE="${COMM_TOPOLOGY_VALUE_SCHEDULER_MODE:-static_sensitivity_staleness}"
COMM_TOPOLOGY_VALUE_BYTE_BUDGET_MB="${COMM_TOPOLOGY_VALUE_BYTE_BUDGET_MB:-0}"
COMM_TOPOLOGY_VALUE_MIN_SCORE_RATIO="${COMM_TOPOLOGY_VALUE_MIN_SCORE_RATIO:-0}"
COMM_TOPOLOGY_VALUE_BUDGET_PACING="${COMM_TOPOLOGY_VALUE_BUDGET_PACING:-true}"
COMM_TOPOLOGY_INTERFACE_MODEL="${COMM_TOPOLOGY_INTERFACE_MODEL:-false}"
COMM_TOPOLOGY_INTERFACE_MODEL_PAYLOAD="${COMM_TOPOLOGY_INTERFACE_MODEL_PAYLOAD:-direction_block}"
COMM_TOPOLOGY_INTERFACE_MODEL_LOCAL_MERIT="${COMM_TOPOLOGY_INTERFACE_MODEL_LOCAL_MERIT:-true}"
COMM_TOPOLOGY_BOUNDARY_CANDIDATE="${COMM_TOPOLOGY_BOUNDARY_CANDIDATE:-false}"
COMM_TOPOLOGY_BOUNDARY_SURROGATE="${COMM_TOPOLOGY_BOUNDARY_SURROGATE:-false}"
COMM_TOPOLOGY_BOUNDARY_SURROGATE_STALE_GAIN="${COMM_TOPOLOGY_BOUNDARY_SURROGATE_STALE_GAIN:-1}"
COMM_TOPOLOGY_REDUCED_INTERFACE_MODEL="${COMM_TOPOLOGY_REDUCED_INTERFACE_MODEL:-false}"
COMM_TOPOLOGY_REDUCED_INTERFACE_WEIGHT="${COMM_TOPOLOGY_REDUCED_INTERFACE_WEIGHT:-0.05}"
COMM_TOPOLOGY_REDUCED_INTERFACE_MAX_LOCAL_ITERS="${COMM_TOPOLOGY_REDUCED_INTERFACE_MAX_LOCAL_ITERS:-0}"
COMM_TOPOLOGY_REDUCED_INTERFACE_CANDIDATE="${COMM_TOPOLOGY_REDUCED_INTERFACE_CANDIDATE:-false}"
STALE_BOUNDARY_PROXIMAL="${STALE_BOUNDARY_PROXIMAL:-false}"
STALE_BOUNDARY_PROXIMAL_WEIGHT="${STALE_BOUNDARY_PROXIMAL_WEIGHT:-0}"
STALE_BOUNDARY_PREDICTION="${STALE_BOUNDARY_PREDICTION:-false}"
STALE_BOUNDARY_PREDICTION_GAIN="${STALE_BOUNDARY_PREDICTION_GAIN:-1}"
SYNC_AMM_REFERENCE_AFTER_LOCAL_GRADIENT_CORRECTION="${SYNC_AMM_REFERENCE_AFTER_LOCAL_GRADIENT_CORRECTION:-true}"
GLOBAL_GRADIENT_CORRECTION="${GLOBAL_GRADIENT_CORRECTION:-false}"
GLOBAL_GRADIENT_CORRECTION_STEP="${GLOBAL_GRADIENT_CORRECTION_STEP:-1e-3}"
GLOBAL_GRADIENT_CORRECTION_STEPS="${GLOBAL_GRADIENT_CORRECTION_STEPS:-}"
RESET_LOCAL_HISTORY_AFTER_GLOBAL_CORRECTION="${RESET_LOCAL_HISTORY_AFTER_GLOBAL_CORRECTION:-false}"
SYNC_AMM_REFERENCE_AFTER_GLOBAL_CORRECTION="${SYNC_AMM_REFERENCE_AFTER_GLOBAL_CORRECTION:-false}"
AMM_ETA0="${AMM_ETA0:-5e-4}"
AMM_ETA1="${AMM_ETA1:-2.5e-2}"
AMM_PSI="${AMM_PSI:-1e-10}"
AMM_PHI="${AMM_PHI:-1e-6}"
AMM_GAMMA_SCALE="${AMM_GAMMA_SCALE:-1}"
AMM_GAMMA_SCALES="${AMM_GAMMA_SCALES:-}"
AMM_ACCEPTED_DELTA="${AMM_ACCEPTED_DELTA:-5e-4}"
AMM_OSCILLATION_COUNT_PERIOD="${AMM_OSCILLATION_COUNT_PERIOD:-15}"
AMM_MAX_OSCILLATIONS="${AMM_MAX_OSCILLATIONS:-12}"
AMM_PROXIMAL_START="${AMM_PROXIMAL_START:-false}"
AMM_DPGO_RESTART_FALLBACK="${AMM_DPGO_RESTART_FALLBACK:-false}"
AMM_DPGO_SURROGATE_PARITY="${AMM_DPGO_SURROGATE_PARITY:-false}"
AMM_BASELINE_SURROGATE_STATE="${AMM_BASELINE_SURROGATE_STATE:-false}"
AMM_DPGO_RECURSIVE_SIMPLE_STATE="${AMM_DPGO_RECURSIVE_SIMPLE_STATE:-false}"
AMM_RECURSIVE_SIMPLE_REANCHOR_PERIOD="${AMM_RECURSIVE_SIMPLE_REANCHOR_PERIOD:-0}"
AMM_DPGO_STRICT_REFINED_GATE="${AMM_DPGO_STRICT_REFINED_GATE:-false}"
AMM_DPGO_RECOVER_TRANSLATIONS_AFTER_PROXIMAL="${AMM_DPGO_RECOVER_TRANSLATIONS_AFTER_PROXIMAL:-false}"
AMM_DPGO_REFINED_STARTS_AT_RECOVERED_PROXIMAL="${AMM_DPGO_REFINED_STARTS_AT_RECOVERED_PROXIMAL:-false}"
AMM_DPGO_MIXED_SURROGATE_PORTFOLIO="${AMM_DPGO_MIXED_SURROGATE_PORTFOLIO:-false}"
AMM_MIXED_SURROGATE_SKIP_SIMPLE_AFTER_TRUE_LOCAL_STREAK="${AMM_MIXED_SURROGATE_SKIP_SIMPLE_AFTER_TRUE_LOCAL_STREAK:-0}"
AMM_MIXED_SURROGATE_FORCE_SIMPLE_EVERY_SKIPPED_ROUNDS="${AMM_MIXED_SURROGATE_FORCE_SIMPLE_EVERY_SKIPPED_ROUNDS:-0}"
AMM_COOLDOWN_AFTER_REJECTED="${AMM_COOLDOWN_AFTER_REJECTED:-0}"
AMM_PROX_RESET_SKIP_REFINED_SOLVE="${AMM_PROX_RESET_SKIP_REFINED_SOLVE:-false}"
AMM_DPGO_PROXIMAL_FALLBACK_ONLY="${AMM_DPGO_PROXIMAL_FALLBACK_ONLY:-false}"
AMM_LAZY_PLAIN_AFTER_CERTIFICATE="${AMM_LAZY_PLAIN_AFTER_CERTIFICATE:-false}"
AMM_SURROGATE_FIRST_EXACT_EVALUATION="${AMM_SURROGATE_FIRST_EXACT_EVALUATION:-false}"
AMM_MAX_SOFT_RESTART_HITS0="${AMM_MAX_SOFT_RESTART_HITS0:-10}"
AMM_MAX_SOFT_RESTART_HITS1="${AMM_MAX_SOFT_RESTART_HITS1:-25}"
AMM_LOCAL_MERIT_FILTER="${AMM_LOCAL_MERIT_FILTER:-true}"
AMM_LOCAL_MERIT_COST_TIE_TOLERANCE="${AMM_LOCAL_MERIT_COST_TIE_TOLERANCE:-1e-4}"
TRACE_AMM="${TRACE_AMM:-false}"
PROFILE_OPTIMIZER="${PROFILE_OPTIMIZER:-false}"
CANDIDATE_EVALUATION_CACHE="${CANDIDATE_EVALUATION_CACHE:-false}"
CANDIDATE_OBJECT_REUSE="${CANDIDATE_OBJECT_REUSE:-false}"
REDUCED_ADAPTIVE_PORTFOLIO_CERTIFIED_FAST_PATH="${REDUCED_ADAPTIVE_PORTFOLIO_CERTIFIED_FAST_PATH:-false}"
REDUCED_ROTATION_DIRECT_OBJECTIVE="${REDUCED_ROTATION_DIRECT_OBJECTIVE:-false}"
FUSED_CANDIDATE_EVALUATION="${FUSED_CANDIDATE_EVALUATION:-false}"
LAZY_CANDIDATE_GRADIENT_EVALUATION="${LAZY_CANDIDATE_GRADIENT_EVALUATION:-false}"
LAZY_SOLVER_START_GRADIENT_EVALUATION="${LAZY_SOLVER_START_GRADIENT_EVALUATION:-false}"
LAZY_SURROGATE_CANDIDATE_GRADIENT_EVALUATION="${LAZY_SURROGATE_CANDIDATE_GRADIENT_EVALUATION:-false}"
REDUCED_ROTATION_CURVATURE_CAUCHY_CANDIDATE="${REDUCED_ROTATION_CURVATURE_CAUCHY_CANDIDATE:-false}"
REDUCED_ROTATION_CURVATURE_FALLBACK_CANDIDATE="${REDUCED_ROTATION_CURVATURE_FALLBACK_CANDIDATE:-false}"
REDUCED_ROTATION_GRADIENT_BOUNDARY_CANDIDATE="${REDUCED_ROTATION_GRADIENT_BOUNDARY_CANDIDATE:-true}"
REDUCED_ROTATION_SURROGATE_TCG_ACCEPT="${REDUCED_ROTATION_SURROGATE_TCG_ACCEPT:-false}"
REDUCED_ROTATION_SKIP_REDUNDANT_CANDIDATE_PROJECTION="${REDUCED_ROTATION_SKIP_REDUNDANT_CANDIDATE_PROJECTION:-false}"
REDUCED_ROTATION_PACKED_CHOLESKY_PROJECT="${REDUCED_ROTATION_PACKED_CHOLESKY_PROJECT:-false}"
REDUCED_ROTATION_PACKED_TCG="${REDUCED_ROTATION_PACKED_TCG:-false}"
REDUCED_ROTATION_PACKED_RIEMANNIAN_HVP="${REDUCED_ROTATION_PACKED_RIEMANNIAN_HVP:-false}"
REDUCED_ROTATION_COMPACT_HVP="${REDUCED_ROTATION_COMPACT_HVP:-false}"
REDUCED_ROTATION_PRECOMPUTED_RESPONSE_HVP="${REDUCED_ROTATION_PRECOMPUTED_RESPONSE_HVP:-false}"
PRINT_ITERATION_SUMMARY="${PRINT_ITERATION_SUMMARY:-true}"
SAVE="${SAVE:-true}"
SAVE_ITERATION_ESTIMATES="${SAVE_ITERATION_ESTIMATES:-false}"
DATASET_FILTER="${DATASETS:-}"
if [[ -z "${OUT_ROOT:-}" && -n "${OUTPUT_DIR:-}" ]]; then
  OUT_ROOT="${OUTPUT_DIR}"
fi
OUT_ROOT="${OUT_ROOT:-${ROOT_DIR}/results/manual_dpgo_mm_six_$(date +%Y%m%d_%H%M%S)}"
DRY_RUN="${DRY_RUN:-false}"
METHOD_NAME="${METHOD_NAME:-manual_dpgo_mm}"

if [[ "${OUT_ROOT}" != /* ]]; then
  OUT_ROOT="${ROOT_DIR}/${OUT_ROOT}"
fi

LOG_ROOT="${OUT_ROOT}/logs"
RUN_ROOT="${OUT_ROOT}/runs"
SUMMARY_CSV="${OUT_ROOT}/summary.csv"

sanitize() {
  local value="$1"
  printf '%s' "${value}" | tr '[:upper:]' '[:lower:]'
}

dataset_suffix() {
  local scheme="$1"
  local accelerated="$2"
  scheme="$(sanitize "${scheme}")"
  accelerated="$(sanitize "${accelerated}")"
  if [[ "${scheme}" == "auto" ]]; then
    if [[ "${accelerated}" == "true" || "${accelerated}" == "1" || "${accelerated}" == "yes" || "${accelerated}" == "on" ]]; then
      printf '%s\n' "amm"
    else
      printf '%s\n' "mm"
    fi
  else
    printf '%s\n' "${scheme}"
  fi
}

METHOD_SUFFIX="$(dataset_suffix "${SCHEME}" "${ACCELERATED}")"
DRY_RUN_NORMALIZED="$(sanitize "${DRY_RUN}")"
IS_DRY_RUN=false
if [[ "${DRY_RUN}" == "1" || "${DRY_RUN_NORMALIZED}" == "true" ]]; then
  IS_DRY_RUN=true
fi

if [[ "${IS_DRY_RUN}" != "true" && ! -x "${BIN}" ]]; then
  echo "Missing executable: ${BIN}" >&2
  echo "Build it first: cmake --build build --target manual-dpgo-mm-example -j2" >&2
  exit 1
fi

declare -A DATASET_PATHS=(
  ["parking-garage"]="data/parking-garage.g2o"
  ["sphere"]="data/sphere2500.g2o"
  ["torus"]="data/torus3D.g2o"
  ["tinyGrid3D"]="data/tinyGrid3D.g2o"
  ["tinyGrid"]="data/tinyGrid3D.g2o"
  ["smallGrid3D"]="data/smallGrid3D.g2o"
  ["grid3D"]="data/grid3D.g2o"
  ["rim"]="data/rim.g2o"
  ["cubicle"]="data/cubicle.g2o"
  ["CSAIL"]="data/CSAIL.g2o"
  ["inter"]="data/input_INTEL_g2o.g2o"
  ["MITb"]="data/input_MITb_g2o.g2o"
  ["ais2klinik"]="data/ais2klinik.g2o"
  ["manhattan"]="data/input_M3500_g2o.g2o"
)

DATASET_ORDER=("parking-garage" "sphere" "torus" "CSAIL" "inter" "manhattan")
if [[ -n "${DATASET_FILTER}" ]]; then
  IFS=',' read -r -a DATASET_ORDER <<< "${DATASET_FILTER}"
fi

mkdir -p "${LOG_ROOT}" "${RUN_ROOT}"

printf 'dataset,method,status,scheme,local_solver,global_cost,gradient,total_comm_poses,total_comm_mb,solver_time_per_node_sec,wall_time_sec,result_path,output_dir,estimate_path,iter_summary_path,log_path\n' > "${SUMMARY_CSV}"
echo "THREAD_CONFIG OMP_NUM_THREADS=${OMP_NUM_THREADS} OPENBLAS_NUM_THREADS=${OPENBLAS_NUM_THREADS} MKL_NUM_THREADS=${MKL_NUM_THREADS} BLIS_NUM_THREADS=${BLIS_NUM_THREADS} VECLIB_MAXIMUM_THREADS=${VECLIB_MAXIMUM_THREADS} NUMEXPR_NUM_THREADS=${NUMEXPR_NUM_THREADS}"

run_case() {
  local dataset="$1"
  local data_path="$2"
  local run_dir="$3"
  local log_path="$4"

  local rel_path
  rel_path="${DATASET_PATHS[${dataset}]:-}"
  local base_name="${data_path##*/}"
  base_name="${base_name%.g2o}"
  local result_path="${run_dir}/results_chordal_${base_name}_${NUM_ROBOTS}_${METHOD_SUFFIX}_${LOCAL_SOLVER}.txt"
  local estimate_path="${run_dir}/estimates_trivial.txt"
  local iter_summary_path="${run_dir}/iteration_summary.csv"
  local external_initial_estimate_path="${EXTERNAL_INITIAL_ESTIMATE}"
  if [[ -z "${external_initial_estimate_path}" && -n "${EXTERNAL_INITIAL_ESTIMATE_DIR}" ]]; then
    external_initial_estimate_path="${EXTERNAL_INITIAL_ESTIMATE_DIR}/${dataset}_estimates_trivial.txt"
  fi

  mkdir -p "${run_dir}"

  if [[ ! -f "${data_path}" ]]; then
    echo "[${dataset}] missing dataset: ${data_path}" | tee "${log_path}"
    printf '%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s\n' \
      "${dataset}" "${METHOD_NAME}" "missing_dataset" "${SCHEME}" "${LOCAL_SOLVER}" \
      "" "" "" "" "" "" "${result_path}" "${run_dir}" "${estimate_path}" "${iter_summary_path}" "${log_path}" >> "${SUMMARY_CSV}"
    return
  fi
  if [[ -n "${external_initial_estimate_path}" && ! -f "${external_initial_estimate_path}" ]]; then
    echo "[${dataset}] missing external initial estimate: ${external_initial_estimate_path}" | tee "${log_path}"
    exit 1
  fi

  echo "=== manual-DPGO-MM ${dataset}: ${rel_path} ==="
  local cmd=(
    "${BIN}"
    --dataset "${data_path}"
    --num_nodes "${NUM_ROBOTS}"
    --iters "${MAX_ITERS}"
    --scheme "${SCHEME}"
    --accelerated "${ACCELERATED}"
    --dist_init "${DIST_INIT}"
    --dist_init_refinement_rounds "${DIST_INIT_REFINEMENT_ROUNDS}"
    --dist_init_fixed_neighbor_chordal_refit "${DIST_INIT_FIXED_NEIGHBOR_CHORDAL_REFIT}"
    --local_solver "${LOCAL_SOLVER}"
    --reduced_rotation_preconditioner "${REDUCED_ROTATION_PRECONDITIONER}"
    --reduced_surrogate_mode "${REDUCED_SURROGATE_MODE}"
    --surrogate_mode "${SURROGATE_MODE}"
    --edge_split_theta_mode "${EDGE_SPLIT_THETA_MODE}"
    --edge_split_theta_default "${EDGE_SPLIT_THETA_DEFAULT}"
    --edge_split_theta_min "${EDGE_SPLIT_THETA_MIN}"
    --edge_split_theta_max "${EDGE_SPLIT_THETA_MAX}"
    --edge_split_theta_candidates "${EDGE_SPLIT_THETA_CANDIDATES}"
    --mm_accelerator "${MM_ACCELERATOR}"
    --mm_safeguard "${MM_SAFEGUARD}"
    --debug_surrogate_bound_check "${DEBUG_SURROGATE_BOUND_CHECK}"
    --debug_surrogate_bound_samples "${DEBUG_SURROGATE_BOUND_SAMPLES}"
    --feh_linear_backend "${FEH_LINEAR_BACKEND}"
    --feh_schur_warm_start "${FEH_SCHUR_WARM_START}"
    --feh_final_polish_rtr "${FEH_FINAL_POLISH_RTR}"
    --feh_schur_damping "${FEH_SCHUR_DAMPING}"
    --feh_linear_rel_tol "${FEH_LINEAR_REL_TOL}"
    --feh_linear_abs_tol "${FEH_LINEAR_ABS_TOL}"
    --feh_linear_max_iters "${FEH_LINEAR_MAX_ITERS}"
    --feh_linear_block_jacobi "${FEH_LINEAR_BLOCK_JACOBI}"
    --feh_sparse_matvec "${FEH_SPARSE_MATVEC}"
    --feh_precond_translation_schur "${FEH_PRECOND_TRANSLATION_SCHUR}"
    --feh_precond_local_chain "${FEH_PRECOND_LOCAL_CHAIN}"
    --feh_precond_translation_block "${FEH_PRECOND_TRANSLATION_BLOCK}"
    --feh_precond_translation_sparse_schur "${FEH_PRECOND_TRANSLATION_SPARSE_SCHUR}"
    --feh_precond_translation_local_schur "${FEH_PRECOND_TRANSLATION_LOCAL_SCHUR}"
    --feh_precond_translation_local_schur_max_poses "${FEH_PRECOND_TRANSLATION_LOCAL_SCHUR_MAX_POSES}"
    --feh_precond_laplacian_deflation "${FEH_PRECOND_LAPLACIAN_DEFLATION}"
    --feh_precond_laplacian_deflation_basis_size "${FEH_PRECOND_LAPLACIAN_DEFLATION_BASIS_SIZE}"
    --feh_precond_laplacian_deflation_max_eigen_poses "${FEH_PRECOND_LAPLACIAN_DEFLATION_MAX_EIGEN_POSES}"
    --feh_precond_reduced_rotation "${FEH_PRECOND_REDUCED_ROTATION}"
    --feh_reduced_rotation_initial_guess "${FEH_REDUCED_ROTATION_INITIAL_GUESS}"
    --feh_translation_recovery_initial_guess "${FEH_TRANSLATION_RECOVERY_INITIAL_GUESS}"
    --feh_rqn_warm_start "${FEH_RQN_WARM_START}"
    --feh_precond_rqn_memory "${FEH_PRECOND_RQN_MEMORY}"
    --feh_rqn_memory_size "${FEH_RQN_MEMORY_SIZE}"
    --feh_rqn_min_curvature_ratio "${FEH_RQN_MIN_CURVATURE_RATIO}"
    --feh_warm_start_max_norm "${FEH_WARM_START_MAX_NORM}"
    --feh_warm_start_backtracking_steps "${FEH_WARM_START_BACKTRACKING_STEPS}"
    --feh_select_best_backtracking "${FEH_SELECT_BEST_BACKTRACKING}"
    --feh_step_pareto_selector "${FEH_STEP_PARETO_SELECTOR}"
    --feh_step_pareto_min_decrease_ratio "${FEH_STEP_PARETO_MIN_DECREASE_RATIO}"
    --feh_backtracking_shared_pose_prox_weight "${FEH_BACKTRACKING_SHARED_POSE_PROX_WEIGHT}"
    --feh_projected_model_rho_guard "${FEH_PROJECTED_MODEL_RHO_GUARD}"
    --feh_projected_model_rho_eta "${FEH_PROJECTED_MODEL_RHO_ETA}"
    --feh_active_separator_correction "${FEH_ACTIVE_SEPARATOR_CORRECTION}"
    --feh_active_separator_step_cap "${FEH_ACTIVE_SEPARATOR_STEP_CAP}"
    --feh_active_separator_block_jacobi "${FEH_ACTIVE_SEPARATOR_BLOCK_JACOBI}"
    --feh_active_separator_compact_schur "${FEH_ACTIVE_SEPARATOR_COMPACT_SCHUR}"
    --feh_active_separator_lm_schur "${FEH_ACTIVE_SEPARATOR_LM_SCHUR}"
    --feh_active_separator_lm_schur_max_boundary_poses "${FEH_ACTIVE_SEPARATOR_LM_SCHUR_MAX_BOUNDARY_POSES}"
    --feh_active_separator_lm_schur_max_private_cols "${FEH_ACTIVE_SEPARATOR_LM_SCHUR_MAX_PRIVATE_COLS}"
    --feh_active_separator_lm_schur_damping "${FEH_ACTIVE_SEPARATOR_LM_SCHUR_DAMPING}"
    --feh_active_separator_lm_schur_backtracking_steps "${FEH_ACTIVE_SEPARATOR_LM_SCHUR_BACKTRACKING_STEPS}"
    --feh_active_separator_lm_schur_min_cost_improvement "${FEH_ACTIVE_SEPARATOR_LM_SCHUR_MIN_COST_IMPROVEMENT}"
    --feh_active_separator_lm_schur_max_rounds "${FEH_ACTIVE_SEPARATOR_LM_SCHUR_MAX_ROUNDS}"
    --feh_active_separator_lm_schur_score_mode "${FEH_ACTIVE_SEPARATOR_LM_SCHUR_SCORE_MODE}"
    --feh_active_separator_lm_schur_gradient_guard "${FEH_ACTIVE_SEPARATOR_LM_SCHUR_GRADIENT_GUARD}"
    --feh_active_separator_lm_schur_max_gradient_increase_ratio "${FEH_ACTIVE_SEPARATOR_LM_SCHUR_MAX_GRADIENT_INCREASE_RATIO}"
    --feh_translation_recovery_polish "${FEH_TRANSLATION_RECOVERY_POLISH}"
    --feh_translation_recovery_polish_gradient_guard "${FEH_TRANSLATION_RECOVERY_POLISH_GRADIENT_GUARD}"
    --feh_translation_recovery_polish_max_gradient_increase_ratio "${FEH_TRANSLATION_RECOVERY_POLISH_MAX_GRADIENT_INCREASE_RATIO}"
    --feh_translation_recovery_polish_backtracking "${FEH_TRANSLATION_RECOVERY_POLISH_BACKTRACKING}"
    --feh_translation_recovery_polish_backtracking_steps "${FEH_TRANSLATION_RECOVERY_POLISH_BACKTRACKING_STEPS}"
    --feh_translation_recovery_polish_merit_selector "${FEH_TRANSLATION_RECOVERY_POLISH_MERIT_SELECTOR}"
    --feh_translation_recovery_polish_merit_min_cost_recovery_ratio "${FEH_TRANSLATION_RECOVERY_POLISH_MERIT_MIN_COST_RECOVERY_RATIO}"
    --feh_translation_recovery_polish_selected_only "${FEH_TRANSLATION_RECOVERY_POLISH_SELECTED_ONLY}"
    --feh_translation_recovery_step_trials "${FEH_TRANSLATION_RECOVERY_STEP_TRIALS}"
    --feh_local_portfolio "${FEH_LOCAL_PORTFOLIO}"
    --manual_full_portfolio "${MANUAL_FULL_PORTFOLIO}"
    --feh_schwarz_presmoothing "${FEH_SCHWARZ_PRESMOOTHING}"
    --feh_schwarz_sweeps "${FEH_SCHWARZ_SWEEPS}"
    --feh_schwarz_max_block_norm "${FEH_SCHWARZ_MAX_BLOCK_NORM}"
    --feh_schwarz_block_mode "${FEH_SCHWARZ_BLOCK_MODE}"
    --local_max_iterations "${LOCAL_MAX_ITERATIONS}"
    --local_max_iterations_accepted "${LOCAL_MAX_ITERATIONS_ACCEPTED}"
    --local_max_tcg_iterations "${LOCAL_MAX_TCG_ITERATIONS}"
    --local_grad_norm_tol "${LOCAL_GRAD_NORM_TOL}"
    --record_local_model_diagnostics "${RECORD_LOCAL_MODEL_DIAGNOSTICS}"
    --parallel_local_solves "${PARALLEL_LOCAL_SOLVES}"
    --adaptive_reduced_tcg "${ADAPTIVE_REDUCED_TCG}"
    --adaptive_reduced_tcg_max_iterations "${ADAPTIVE_REDUCED_TCG_MAX_ITERATIONS}"
    --adaptive_reduced_tcg_gradient_ratio "${ADAPTIVE_REDUCED_TCG_GRADIENT_RATIO}"
    --reduced_rotation_tcg_relative_tolerance "${REDUCED_ROTATION_TCG_RELATIVE_TOLERANCE}"
    --local_state_extrapolation "${LOCAL_STATE_EXTRAPOLATION}"
    --local_state_extrapolation_gamma "${LOCAL_STATE_EXTRAPOLATION_GAMMA}"
    --local_state_extrapolation_use_active_surrogate "${LOCAL_STATE_EXTRAPOLATION_USE_ACTIVE_SURROGATE}"
    --local_boundary_proximal_candidate "${LOCAL_BOUNDARY_PROXIMAL_CANDIDATE}"
    --local_boundary_proximal_weight "${LOCAL_BOUNDARY_PROXIMAL_WEIGHT}"
    --local_model_g_extrapolation "${LOCAL_MODEL_G_EXTRAPOLATION}"
    --local_model_g_extrapolation_gamma "${LOCAL_MODEL_G_EXTRAPOLATION_GAMMA}"
    --coupled_state_g_extrapolation "${COUPLED_STATE_G_EXTRAPOLATION}"
    --coupled_state_g_extrapolation_gamma "${COUPLED_STATE_G_EXTRAPOLATION_GAMMA}"
    --local_anderson_acceleration "${LOCAL_ANDERSON_ACCELERATION}"
    --local_anderson_max_alpha "${LOCAL_ANDERSON_MAX_ALPHA}"
    --local_squarem_max_alpha "${LOCAL_SQUAREM_MAX_ALPHA}"
    --local_candidate_cost_tie_tolerance "${LOCAL_CANDIDATE_COST_TIE_TOLERANCE}"
    --global_state_extrapolation "${GLOBAL_STATE_EXTRAPOLATION}"
    --global_state_extrapolation_gamma "${GLOBAL_STATE_EXTRAPOLATION_GAMMA}"
    --global_anderson_acceleration "${GLOBAL_ANDERSON_ACCELERATION}"
    --global_anderson_max_alpha "${GLOBAL_ANDERSON_MAX_ALPHA}"
    --local_gradient_correction "${LOCAL_GRADIENT_CORRECTION}"
    --local_gradient_correction_step "${LOCAL_GRADIENT_CORRECTION_STEP}"
    --local_gradient_correction_shared_step "${LOCAL_GRADIENT_CORRECTION_SHARED_STEP}"
    --local_gradient_correction_neighborhood_step "${LOCAL_GRADIENT_CORRECTION_NEIGHBORHOOD_STEP}"
    --local_gradient_correction_curvature_step "${LOCAL_GRADIENT_CORRECTION_CURVATURE_STEP}"
    --local_gradient_correction_coupled_direction "${LOCAL_GRADIENT_CORRECTION_COUPLED_DIRECTION}"
    --local_gradient_correction_coupled_direction_budget_fraction "${LOCAL_GRADIENT_CORRECTION_COUPLED_DIRECTION_BUDGET_FRACTION}"
    --local_gradient_correction_coupled_direction_max_packets_per_receiver "${LOCAL_GRADIENT_CORRECTION_COUPLED_DIRECTION_MAX_PACKETS_PER_RECEIVER}"
    --local_gradient_correction_coupled_direction_topk_entries "${LOCAL_GRADIENT_CORRECTION_COUPLED_DIRECTION_TOPK_ENTRIES}"
    --local_gradient_correction_coupled_direction_min_score "${LOCAL_GRADIENT_CORRECTION_COUPLED_DIRECTION_MIN_SCORE}"
    --local_gradient_correction_coupled_direction_min_score_ratio "${LOCAL_GRADIENT_CORRECTION_COUPLED_DIRECTION_MIN_SCORE_RATIO}"
    --local_gradient_correction_coupled_direction_byte_budget_mb "${LOCAL_GRADIENT_CORRECTION_COUPLED_DIRECTION_BYTE_BUDGET_MB}"
    --local_gradient_correction_boundary_only "${LOCAL_GRADIENT_CORRECTION_BOUNDARY_ONLY}"
    --local_gradient_correction_block_jacobi "${LOCAL_GRADIENT_CORRECTION_BLOCK_JACOBI}"
    --local_gradient_correction_compact_schur "${LOCAL_GRADIENT_CORRECTION_COMPACT_SCHUR}"
    --local_gradient_correction_compact_schur_max_boundary_poses "${LOCAL_GRADIENT_CORRECTION_COMPACT_SCHUR_MAX_BOUNDARY_POSES}"
    --local_gradient_correction_compact_schur_max_private_cols "${LOCAL_GRADIENT_CORRECTION_COMPACT_SCHUR_MAX_PRIVATE_COLS}"
    --local_gradient_correction_compact_schur_damping "${LOCAL_GRADIENT_CORRECTION_COMPACT_SCHUR_DAMPING}"
    --local_gradient_correction_compact_schur_min_cost_decrease "${LOCAL_GRADIENT_CORRECTION_COMPACT_SCHUR_MIN_COST_DECREASE}"
    --local_gradient_correction_compact_schur_gradient_guard "${LOCAL_GRADIENT_CORRECTION_COMPACT_SCHUR_GRADIENT_GUARD}"
    --local_gradient_correction_compact_schur_max_gradient_increase_ratio "${LOCAL_GRADIENT_CORRECTION_COMPACT_SCHUR_MAX_GRADIENT_INCREASE_RATIO}"
    --local_gradient_correction_fresh_neighbor_exchange "${LOCAL_GRADIENT_CORRECTION_FRESH_NEIGHBOR_EXCHANGE}"
    --local_gradient_correction_fresh_min_pose_delta "${LOCAL_GRADIENT_CORRECTION_FRESH_MIN_POSE_DELTA}"
    --local_gradient_correction_fresh_delta_mode "${LOCAL_GRADIENT_CORRECTION_FRESH_DELTA_MODE}"
    --local_gradient_correction_fresh_budget_fraction "${LOCAL_GRADIENT_CORRECTION_FRESH_BUDGET_FRACTION}"
    --local_gradient_correction_fresh_max_poses_per_receiver "${LOCAL_GRADIENT_CORRECTION_FRESH_MAX_POSES_PER_RECEIVER}"
    --local_gradient_correction_inner_rounds "${LOCAL_GRADIENT_CORRECTION_INNER_ROUNDS}"
    --local_gradient_correction_max_rounds "${LOCAL_GRADIENT_CORRECTION_MAX_ROUNDS}"
    --post_exchange_period "${POST_EXCHANGE_PERIOD}"
    --post_exchange_min_pose_delta "${POST_EXCHANGE_MIN_POSE_DELTA}"
    --post_exchange_delta_mode "${POST_EXCHANGE_DELTA_MODE}"
    --post_exchange_budget_fraction "${POST_EXCHANGE_BUDGET_FRACTION}"
    --post_exchange_max_poses_per_receiver "${POST_EXCHANGE_MAX_POSES_PER_RECEIVER}"
    --comm_topology_file "${COMM_TOPOLOGY_FILE}"
    --comm_topology_initial_full "${COMM_TOPOLOGY_INITIAL_FULL}"
    --comm_topology_max_relay_hops "${COMM_TOPOLOGY_MAX_RELAY_HOPS}"
    --comm_topology_hop_budget_fraction "${COMM_TOPOLOGY_HOP_BUDGET_FRACTION}"
    --comm_topology_stale_aware_relay_score "${COMM_TOPOLOGY_STALE_AWARE_RELAY_SCORE}"
    --comm_topology_stale_aware_relay_age_gain "${COMM_TOPOLOGY_STALE_AWARE_RELAY_AGE_GAIN}"
    --comm_topology_delta_compression "${COMM_TOPOLOGY_DELTA_COMPRESSION}"
    --comm_topology_delta_mode "${COMM_TOPOLOGY_DELTA_MODE}"
    --comm_topology_delta_topk "${COMM_TOPOLOGY_DELTA_TOPK}"
    --comm_topology_delta_max_reconstruction_error "${COMM_TOPOLOGY_DELTA_MAX_RECONSTRUCTION_ERROR}"
    --comm_topology_lifted_delta_compression "${COMM_TOPOLOGY_LIFTED_DELTA_COMPRESSION}"
    --comm_topology_lifted_delta_max_reconstruction_error "${COMM_TOPOLOGY_LIFTED_DELTA_MAX_RECONSTRUCTION_ERROR}"
    --comm_topology_lifted_delta_rank "${COMM_TOPOLOGY_LIFTED_DELTA_RANK}"
    --comm_topology_value_scheduler "${COMM_TOPOLOGY_VALUE_SCHEDULER}"
    --comm_topology_value_scheduler_mode "${COMM_TOPOLOGY_VALUE_SCHEDULER_MODE}"
    --comm_topology_value_byte_budget_mb "${COMM_TOPOLOGY_VALUE_BYTE_BUDGET_MB}"
    --comm_topology_value_min_score_ratio "${COMM_TOPOLOGY_VALUE_MIN_SCORE_RATIO}"
    --comm_topology_value_budget_pacing "${COMM_TOPOLOGY_VALUE_BUDGET_PACING}"
    --comm_topology_interface_model "${COMM_TOPOLOGY_INTERFACE_MODEL}"
    --comm_topology_interface_model_payload "${COMM_TOPOLOGY_INTERFACE_MODEL_PAYLOAD}"
    --comm_topology_interface_model_local_merit "${COMM_TOPOLOGY_INTERFACE_MODEL_LOCAL_MERIT}"
    --comm_topology_boundary_candidate "${COMM_TOPOLOGY_BOUNDARY_CANDIDATE}"
    --comm_topology_boundary_surrogate "${COMM_TOPOLOGY_BOUNDARY_SURROGATE}"
    --comm_topology_boundary_surrogate_stale_gain "${COMM_TOPOLOGY_BOUNDARY_SURROGATE_STALE_GAIN}"
    --comm_topology_reduced_interface_model "${COMM_TOPOLOGY_REDUCED_INTERFACE_MODEL}"
    --comm_topology_reduced_interface_weight "${COMM_TOPOLOGY_REDUCED_INTERFACE_WEIGHT}"
    --comm_topology_reduced_interface_max_local_iters "${COMM_TOPOLOGY_REDUCED_INTERFACE_MAX_LOCAL_ITERS}"
    --comm_topology_reduced_interface_candidate "${COMM_TOPOLOGY_REDUCED_INTERFACE_CANDIDATE}"
    --stale_boundary_proximal "${STALE_BOUNDARY_PROXIMAL}"
    --stale_boundary_proximal_weight "${STALE_BOUNDARY_PROXIMAL_WEIGHT}"
    --stale_boundary_prediction "${STALE_BOUNDARY_PREDICTION}"
    --stale_boundary_prediction_gain "${STALE_BOUNDARY_PREDICTION_GAIN}"
    --sync_amm_reference_after_local_gradient_correction "${SYNC_AMM_REFERENCE_AFTER_LOCAL_GRADIENT_CORRECTION}"
    --global_gradient_correction "${GLOBAL_GRADIENT_CORRECTION}"
    --global_gradient_correction_step "${GLOBAL_GRADIENT_CORRECTION_STEP}"
    --reset_local_history_after_global_correction "${RESET_LOCAL_HISTORY_AFTER_GLOBAL_CORRECTION}"
    --sync_amm_reference_after_global_correction "${SYNC_AMM_REFERENCE_AFTER_GLOBAL_CORRECTION}"
    --amm_eta0 "${AMM_ETA0}"
    --amm_eta1 "${AMM_ETA1}"
    --amm_psi "${AMM_PSI}"
    --amm_phi "${AMM_PHI}"
    --amm_gamma_scale "${AMM_GAMMA_SCALE}"
    --amm_accepted_delta "${AMM_ACCEPTED_DELTA}"
    --amm_oscillation_count_period "${AMM_OSCILLATION_COUNT_PERIOD}"
    --amm_max_oscillations "${AMM_MAX_OSCILLATIONS}"
    --amm_proximal_start "${AMM_PROXIMAL_START}"
    --amm_dpgo_restart_fallback "${AMM_DPGO_RESTART_FALLBACK}"
    --amm_dpgo_surrogate_parity "${AMM_DPGO_SURROGATE_PARITY}"
    --amm_baseline_surrogate_state "${AMM_BASELINE_SURROGATE_STATE}"
    --amm_dpgo_recursive_simple_state "${AMM_DPGO_RECURSIVE_SIMPLE_STATE}"
    --amm_recursive_simple_reanchor_period "${AMM_RECURSIVE_SIMPLE_REANCHOR_PERIOD}"
    --amm_dpgo_strict_refined_gate "${AMM_DPGO_STRICT_REFINED_GATE}"
    --amm_dpgo_recover_translations_after_proximal "${AMM_DPGO_RECOVER_TRANSLATIONS_AFTER_PROXIMAL}"
    --amm_dpgo_refined_starts_at_recovered_proximal "${AMM_DPGO_REFINED_STARTS_AT_RECOVERED_PROXIMAL}"
    --amm_dpgo_mixed_surrogate_portfolio "${AMM_DPGO_MIXED_SURROGATE_PORTFOLIO}"
    --amm_mixed_surrogate_skip_simple_after_true_local_streak "${AMM_MIXED_SURROGATE_SKIP_SIMPLE_AFTER_TRUE_LOCAL_STREAK}"
    --amm_mixed_surrogate_force_simple_every_skipped_rounds "${AMM_MIXED_SURROGATE_FORCE_SIMPLE_EVERY_SKIPPED_ROUNDS}"
    --amm_cooldown_after_rejected "${AMM_COOLDOWN_AFTER_REJECTED}"
    --amm_prox_reset_skip_refined_solve "${AMM_PROX_RESET_SKIP_REFINED_SOLVE}"
    --amm_dpgo_proximal_fallback_only "${AMM_DPGO_PROXIMAL_FALLBACK_ONLY}"
    --amm_lazy_plain_after_certificate "${AMM_LAZY_PLAIN_AFTER_CERTIFICATE}"
    --amm_surrogate_first_exact_evaluation "${AMM_SURROGATE_FIRST_EXACT_EVALUATION}"
    --amm_max_soft_restart_hits0 "${AMM_MAX_SOFT_RESTART_HITS0}"
    --amm_max_soft_restart_hits1 "${AMM_MAX_SOFT_RESTART_HITS1}"
    --amm_local_merit_filter "${AMM_LOCAL_MERIT_FILTER}"
    --amm_local_merit_cost_tie_tolerance "${AMM_LOCAL_MERIT_COST_TIE_TOLERANCE}"
    --trace_amm "${TRACE_AMM}"
    --profile_optimizer "${PROFILE_OPTIMIZER}"
    --candidate_evaluation_cache "${CANDIDATE_EVALUATION_CACHE}"
    --candidate_object_reuse "${CANDIDATE_OBJECT_REUSE}"
    --reduced_adaptive_portfolio_certified_fast_path "${REDUCED_ADAPTIVE_PORTFOLIO_CERTIFIED_FAST_PATH}"
    --reduced_rotation_direct_objective "${REDUCED_ROTATION_DIRECT_OBJECTIVE}"
    --fused_candidate_evaluation "${FUSED_CANDIDATE_EVALUATION}"
    --lazy_candidate_gradient_evaluation "${LAZY_CANDIDATE_GRADIENT_EVALUATION}"
    --lazy_solver_start_gradient_evaluation "${LAZY_SOLVER_START_GRADIENT_EVALUATION}"
    --lazy_surrogate_candidate_gradient_evaluation "${LAZY_SURROGATE_CANDIDATE_GRADIENT_EVALUATION}"
    --reduced_rotation_curvature_cauchy_candidate "${REDUCED_ROTATION_CURVATURE_CAUCHY_CANDIDATE}"
    --reduced_rotation_curvature_fallback_candidate "${REDUCED_ROTATION_CURVATURE_FALLBACK_CANDIDATE}"
    --reduced_rotation_gradient_boundary_candidate "${REDUCED_ROTATION_GRADIENT_BOUNDARY_CANDIDATE}"
    --reduced_rotation_surrogate_tcg_accept "${REDUCED_ROTATION_SURROGATE_TCG_ACCEPT}"
    --reduced_rotation_skip_redundant_candidate_projection "${REDUCED_ROTATION_SKIP_REDUNDANT_CANDIDATE_PROJECTION}"
    --print_iteration_summary "${PRINT_ITERATION_SUMMARY}"
    --output_dir "${run_dir}"
    --save_iteration_estimates "${SAVE_ITERATION_ESTIMATES}"
    --save "${SAVE}"
  )
  if [[ -n "${external_initial_estimate_path}" ]]; then
    cmd+=(--external_initial_estimate "${external_initial_estimate_path}")
  fi
  if [[ -n "${LOCAL_STATE_EXTRAPOLATION_GAMMAS}" ]]; then
    cmd+=(--local_state_extrapolation_gammas "${LOCAL_STATE_EXTRAPOLATION_GAMMAS}")
  fi
  if [[ -n "${LOCAL_BOUNDARY_PROXIMAL_WEIGHTS}" ]]; then
    cmd+=(--local_boundary_proximal_weights "${LOCAL_BOUNDARY_PROXIMAL_WEIGHTS}")
  fi
  if [[ -n "${LOCAL_MODEL_G_EXTRAPOLATION_GAMMAS}" ]]; then
    cmd+=(--local_model_g_extrapolation_gammas "${LOCAL_MODEL_G_EXTRAPOLATION_GAMMAS}")
  fi
  if [[ -n "${COUPLED_STATE_G_EXTRAPOLATION_GAMMAS}" ]]; then
    cmd+=(--coupled_state_g_extrapolation_gammas "${COUPLED_STATE_G_EXTRAPOLATION_GAMMAS}")
  fi
  if [[ -n "${GLOBAL_STATE_EXTRAPOLATION_GAMMAS}" ]]; then
    cmd+=(--global_state_extrapolation_gammas "${GLOBAL_STATE_EXTRAPOLATION_GAMMAS}")
  fi
  if [[ -n "${LOCAL_GRADIENT_CORRECTION_STEPS}" ]]; then
    cmd+=(--local_gradient_correction_steps "${LOCAL_GRADIENT_CORRECTION_STEPS}")
  fi
  if [[ -n "${GLOBAL_GRADIENT_CORRECTION_STEPS}" ]]; then
    cmd+=(--global_gradient_correction_steps "${GLOBAL_GRADIENT_CORRECTION_STEPS}")
  fi
  if [[ -n "${AMM_GAMMA_SCALES}" ]]; then
    cmd+=(--amm_gamma_scales "${AMM_GAMMA_SCALES}")
  fi

  if [[ "${IS_DRY_RUN}" == "true" ]]; then
    printf 'DRY_RUN=1 DRAN_REDUCED_ROTATION_PACKED_CHOLESKY_PROJECT=%q DRAN_REDUCED_ROTATION_PACKED_TCG=%q DRAN_REDUCED_ROTATION_PACKED_RIEMANNIAN_HVP=%q DRAN_REDUCED_ROTATION_COMPACT_HVP=%q DRAN_REDUCED_ROTATION_PRECOMPUTED_RESPONSE_HVP=%q ' \
      "${REDUCED_ROTATION_PACKED_CHOLESKY_PROJECT}" \
      "${REDUCED_ROTATION_PACKED_TCG}" \
      "${REDUCED_ROTATION_PACKED_RIEMANNIAN_HVP}" \
      "${REDUCED_ROTATION_COMPACT_HVP}" \
      "${REDUCED_ROTATION_PRECOMPUTED_RESPONSE_HVP}"
    printf '%q ' "${cmd[@]}"
    printf '\n'
    printf '%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s\n' \
      "${dataset}" "${METHOD_NAME}" "dry_run" "${SCHEME}" "${LOCAL_SOLVER}" \
      "" "" "" "" "" "" "${result_path}" "${run_dir}" "${estimate_path}" "${iter_summary_path}" "${log_path}" >> "${SUMMARY_CSV}"
    return
  fi

  local start_ns end_ns
  local status=0
  start_ns="$(date +%s%N)"
  set +e
  DRAN_REDUCED_ROTATION_PACKED_CHOLESKY_PROJECT="${REDUCED_ROTATION_PACKED_CHOLESKY_PROJECT}" \
  DRAN_REDUCED_ROTATION_PACKED_TCG="${REDUCED_ROTATION_PACKED_TCG}" \
  DRAN_REDUCED_ROTATION_PACKED_RIEMANNIAN_HVP="${REDUCED_ROTATION_PACKED_RIEMANNIAN_HVP}" \
  DRAN_REDUCED_ROTATION_COMPACT_HVP="${REDUCED_ROTATION_COMPACT_HVP}" \
  DRAN_REDUCED_ROTATION_PRECOMPUTED_RESPONSE_HVP="${REDUCED_ROTATION_PRECOMPUTED_RESPONSE_HVP}" \
    "${cmd[@]}" 2>&1 | tee "${log_path}"
  status=${PIPESTATUS[0]}
  set -e
  end_ns="$(date +%s%N)"

  local final_objective=""
  local final_gradient=""
  local solver_time_per_node_sec=""
  local wall_time_sec=""
  local total_comm_poses=""
  local total_comm_mb=""

  final_objective="$(awk -F': *' '/^final objective:/ {value=$2} END {print value}' "${log_path}")"
  final_gradient="$(awk -F': *' '/^final gradient:/ {value=$2} END {print value}' "${log_path}")"
  solver_time_per_node_sec="$(awk '/^time:/ {value=$2} END {print value}' "${log_path}")"
  wall_time_sec="$(awk -v start="${start_ns}" -v end="${end_ns}" 'BEGIN {printf "%.9f", (end - start) / 1000000000.0}')"

  if [[ -f "${iter_summary_path}" ]]; then
    total_comm_poses="$(awk -F, 'NR > 1 {value=$7} END {print value}' "${iter_summary_path}")"
    total_comm_mb="$(awk -F, 'NR > 1 {value=$8} END {print value}' "${iter_summary_path}")"
  fi

  local status_text="ok"
  if [[ ${status} -ne 0 || -z "${final_objective}" || -z "${final_gradient}" ]]; then
    status_text="failed"
  fi

  printf '%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s\n' \
    "${dataset}" \
    "${METHOD_NAME}" \
    "${status_text}" \
    "${SCHEME}" \
    "${LOCAL_SOLVER}" \
    "${final_objective}" \
    "${final_gradient}" \
    "${total_comm_poses}" \
    "${total_comm_mb}" \
    "${solver_time_per_node_sec}" \
    "${wall_time_sec}" \
    "${result_path}" \
    "${run_dir}" \
    "${estimate_path}" \
    "${iter_summary_path}" \
    "${log_path}" >> "${SUMMARY_CSV}"
}

for dataset in "${DATASET_ORDER[@]}"; do
  data_path="${ROOT_DIR}/${DATASET_PATHS[${dataset}]:-}"
  run_dir="${RUN_ROOT}/${dataset}"
  log_path="${LOG_ROOT}/${dataset}.log"
  run_case "${dataset}" "${data_path}" "${run_dir}" "${log_path}"
done

echo "Saved summary: ${SUMMARY_CSV}"
echo "Saved logs under: ${LOG_ROOT}"
echo "Saved run directories under: ${RUN_ROOT}"
